const data = [
  {
    name: '.dad',
    entity: 'Fathers.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/dad.svg',
    promoImg: '/images/domains/icann/dad.svg',
  },
  {
    name: '.dance',
    entity: 'Dance.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Dance studios & instructors, nightclubs & music venues, dance teams & troupes, dance shoe, clothing & equipment manufacturers, fans of dance & live performances.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.dance',
    logo: '/images/domains/icann/dance.svg',
    promoImg: '/images/domains/icann/dance.svg',
  },
  {
    name: '.data',
    entity: 'Data.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Dish DBS Corporation.',
      link: 'https://en.wikipedia.org/wiki/Dish_Network',
    },
    notes: [],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/data.svg',
    promoImg: '/images/domains/icann/data.svg',
  },
  {
    name: '.date',
    entity: 'Online dating.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Global Registry Services Ltd.',
      link: 'https://en.wikipedia.org/wiki/GRS_Domains',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.date',
    logo: '/images/domains/icann/date.svg',
    promoImg: '/images/domains/icann/date.svg',
  },
  {
    name: '.dating',
    entity: 'Dating & matchmaker sites.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Dating & matchmaker sites, travel sites & city guides, singles meetup groups, traditional “classified” sites, event businesses.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.dating',
    logo: '/images/domains/icann/dating.svg',
    promoImg: '/images/domains/icann/dating.svg',
  },
  {
    name: '.day',
    entity: 'Day.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`General.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/day.svg',
    promoImg: '/images/domains/icann/day.svg',
  },
  {
    name: '.deal',
    entity: 'Deal.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Amazon Registry Services, Inc.',
      link: 'https://en.wikipedia.org/wiki/Amazon.com',
    },
    notes: [`Sales.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/deal.svg',
    promoImg: '/images/domains/icann/deal.svg',
  },
  {
    name: '.deals',
    entity: 'Deals.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Discount sites, bargain hunters, coupon sites, coupon pages. coupon-themed guides, directories and blogs.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/deals.svg',
    promoImg: '/images/domains/icann/deals.svg',
  },
  {
    name: '.degree',
    entity: 'Degree.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Discount sites, bargain hunters, coupon sites, coupon pages. coupon-themed guides, directories and blogs.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/degree.svg',
    promoImg: '/images/domains/icann/degree.svg',
  },
  {
    name: '.design',
    entity: 'Design.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Brick-and-mortar schools & universities, online universities, other learning courses, other educational resources.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/design.svg',
    promoImg: '/images/domains/icann/design.svg',
  },
  {
    name: '.delivery',
    entity: 'Delivery.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Consumer delivery services, commercial shipping services, transportation services, messenger services, any business that ships their products.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/delivery.svg',
    promoImg: '/images/domains/icann/delivery.svg',
  },
  {
    name: '.democrat',
    entity: 'Democrat.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Political candidates, lobbyists, political parties, fundraising organizations.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/democrat.svg',
    promoImg: '/images/domains/icann/democrat.svg',
  },
  {
    name: '.dental',
    entity: 'Dentists, endodontists, orthodontists.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Dentists, endodontists, orthodontists, retailers selling oral health supplies, wholesale suppliers for dental care.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/dental.svg',
    promoImg: '/images/domains/icann/dental.svg',
  },
  {
    name: '.dentist',
    entity: 'Dentist.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Dentists, endodontists, orthodontists, retailers selling oral health supplies, wholesale suppliers for dental care.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/dentist.svg',
    promoImg: '/images/domains/icann/dentist.svg',
  },
  {
    name: '.design',
    entity: 'Graphic art and fashion.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Top Level Design',
      link: 'https://en.wikipedia.org/wiki/Top_Level_Design',
    },
    notes: [
      `Ben Crawford, CentralNic's CEO, said of the top-level domain, "It has impressive commercial potential, and it will be adopted more quickly than many other TLDs as it caters, among many other groups, to one of the best-informed professions on new Internet developments – website designers".`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.design',
    logo: '/images/domains/icann/design.svg',
    promoImg: '/images/domains/icann/design.svg',
  },
  {
    name: '.dev',
    entity: 'Software development.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [
      `Web developers have been using .dev top-level domains within their internal networks for testing purposes for a long time. However, after Google acquired the TLD, such environments have stopped functioning on some modern web browsers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.dev',
    logo: '/images/domains/icann/dev.svg',
    promoImg: '/images/domains/icann/dev.svg',
  },
  {
    name: '.diamonds',
    entity: 'Diamonds.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Jewelers, diamond wholesalers and retailers, jewelry appraisers and buyers, pawn shops.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/diamonds.svg',
    promoImg: '/images/domains/icann/diamonds.svg',
  },
  {
    name: '.diet',
    entity: 'Diet.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Uniregistry.',
      link: 'https://en.wikipedia.org/wiki/Uniregistry',
    },
    notes: [`Dieting and dietary.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.diet',
    logo: '/images/domains/icann/diet.svg',
    promoImg: '/images/domains/icann/diet.svg',
  },
  {
    name: '.digital',
    entity: 'Digital.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Advertising/Marketing/PR/Design agencies, media buying/production companies (digital & traditional), online event, meetup & gaming sites, technology companies, e-commerce sites.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/digital.svg',
    promoImg: '/images/domains/icann/digital.svg',
  },
  {
    name: '.direct',
    entity: 'Direct.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Direct-to-consumer stores, bargain hunters, transportation services, messenger services, delivery & shipping services.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/direct.svg',
    promoImg: '/images/domains/icann/direct.svg',
  },
  {
    name: '.directory',
    entity: 'Directory.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Listings organizations, name, phone & address directories, online business directories, clubs, groups, & other organizations directories.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.directory',
    logo: '/images/domains/icann/directory.svg',
    promoImg: '/images/domains/icann/directory.svg',
  },
  {
    name: '.discount',
    entity: 'Discount.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Discount sites, bargain hunters, coupon sites, coupon pages, coupon-themed blogs.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/discount.svg',
    promoImg: '/images/domains/icann/discount.svg',
  },
  {
    name: '.diy',
    entity: 'D.I.Y.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Lifestyle Domain Holdings, Inc.',
      link: '',
    },
    notes: [`D.I.Y. - do-it-yourself.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/diy.svg',
    promoImg: '/images/domains/icann/diy.svg',
  },
  {
    name: '.docs',
    entity: 'Docs.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google_Registry',
    },
    notes: [`Technical Documentation.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/docs.svg',
    promoImg: '/images/domains/icann/docs.svg',
  },
  {
    name: '.doctor',
    entity: 'Doctor.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Doctors, any business with “doctor” in the name, other health care providers, PhD experts in any field.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/doctor.svg',
    promoImg: '/images/domains/icann/doctor.svg',
  },
  {
    name: '.dog',
    entity: 'Dog.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Dog breeders, dog walking, grooming & sitting businesses, veterinarians, animal shelters & adoption centers, pet stores & suppliers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/dog.svg',
    promoImg: '/images/domains/icann/dog.svg',
  },
  {
    name: '.domains',
    entity: 'Domains.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Any web-based service, network consultants, domain brokers, resellers and registrars, home-related products and services.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.domains',
    logo: '/images/domains/icann/domains.svg',
    promoImg: '/images/domains/icann/domains.svg',
  },
  {
    name: '.dot',
    entity: 'Dot.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: `Dish DBS Corporation.`,
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/dot.svg',
    promoImg: '/images/domains/icann/dot.svg',
  },
  {
    name: '.download',
    entity: 'Download.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Global Registry Services Ltd.',
      link: 'https://en.wikipedia.org/wiki/GRS_Domains',
    },
    notes: [`Technology.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.download',
    logo: '/images/domains/icann/download.svg',
    promoImg: '/images/domains/icann/download.svg',
  },
  {
    name: '.drive',
    entity: 'Drive.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google_Registry',
    },
    notes: [`Reserved for Google Drive.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Google_Drive',
    logo: '/images/domains/icann/drive.svg',
    promoImg: '/images/domains/icann/drive.svg',
  },
]


export default data;
