const data = [
  {
    name: '.zero',
    entity: 'Zero.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Amazon Registry Services, Inc.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/zero.svg',
    promoImg: '/images/domains/icann/zero.svg',
  },
  {
    name: '.zip',
    entity: 'Zip.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: '',
    },
    notes: [`Digital storage information, providers, and related entities.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/zip.svg',
    promoImg: '/images/domains/icann/zip.svg',
  },
  {
    name: '.zone',
    entity: 'Zone.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Sports fans, technology groups & followers, entertainment, fairs, destinations with a “zone”, city planners & zoning regulators, any topic with a following.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/zone.svg',
    promoImg: '/images/domains/icann/zone.svg',
  },
]

export default data
