const data = [
  {
    name: '.earth',
    entity: 'Earth.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Interlink Co., Ltd.',
      link: '',
    },
    notes: [`Individuals or businesses with a worldwide focus.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/earth.svg',
    promoImg: '/images/domains/icann/earth.svg',
  },
  {
    name: '.eat',
    entity: 'Eat.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`Restaurants and foodies.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/eat.svg',
    promoImg: '/images/domains/icann/eat.svg',
  },
  {
    name: '.eco',
    entity: `Sustainability minded companies, non-profits and professionals.`,
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Big Room Inc.',
      link: '',
    },
    notes: [`Open to anyone pledging a commitment to sustainability action.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/eco.svg',
    promoImg: '/images/domains/icann/eco.svg',
  },
  {
    name: '.education',
    entity: 'Education.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Colleges & universities, public schools, PTAs & other school groups, education research organizations, any organization focused on educating its audience.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/education.svg',
    promoImg: '/images/domains/icann/education.svg',
  },
  {
    name: '.email',
    entity: 'Email.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Advertising/Marketing/PR/Design agencies, email marketing experts, CRM and marketing technology specialists, anyone who wants a memorable email address.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/email.svg',
    promoImg: '/images/domains/icann/email.svg',
  },
  {
    name: '.energy',
    entity: 'Energy.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Electrical, mechanical, chemical, nuclear & thermal energy producers, solar, wind, hydro, bio & other sustainable alternative energy producers, battery manufacturers & oil industry R&D, energy conservation organizations, energy food & drink manufacturers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/energy.svg',
    promoImg: '/images/domains/icann/energy.svg',
  },
  {
    name: '.engineer',
    entity: 'Engineer.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Computer and software engineering companies, civil, electrical, mechanical, and architectural engineering companies, environmental, chemical, geotechnical, and bio engineering companies, engineer training or educational institutions, railroad engineers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/engineer.svg',
    promoImg: '/images/domains/icann/engineer.svg',
  },
  {
    name: '.engineering',
    entity: 'Engineering.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Computer and software engineering companies, civil, electrical, mechanical, and architectural engineering companies, environmental, chemical, geotechnical, and bio engineering companies, engineer training or educational institutions, railroad engineers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.engineering',
    logo: '/images/domains/icann/engineering.svg',
    promoImg: '/images/domains/icann/engineering.svg',
  },
  {
    name: '.edeka',
    entity: 'Edeka.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'EDEKA Verband kaufmännischer Genossenschaften e.V.',
      link: '',
    },
    notes: [`Edeka firms.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/edeka.svg',
    promoImg: '/images/domains/icann/edeka.svg',
  },
  {
    name: '.entertainment',
    entity: 'Entertainment.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Ticket outlets, travel sites & local tourist sites, performance halls, theaters, & music venues, anyone in the entertainment industry, celebrity news sites.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/entertainment.svg',
    promoImg: '/images/domains/icann/entertainment.svg',
  },
  {
    name: '.enterprises',
    entity: 'Enterprises.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Entrepreneurs, startups, parent & holding companies, enterprise SaaS solutions & tech services.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/enterprises.svg',
    promoImg: '/images/domains/icann/enterprises.svg',
  },
  {
    name: '.equipment',
    entity: 'Equipment.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Home improvement stores, construction equipment rentals, construction equipment sales, sporting goods stores.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/equipment.svg',
    promoImg: '/images/domains/icann/equipment.svg',
  },
  {
    name: '.esq',
    entity: `Lawyers, law firms, legal professionals.`,
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`To be restricted to verified lawyers and attorneys.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/esq.svg',
    promoImg: '/images/domains/icann/esq.svg',
  },
  {
    name: '.estate',
    entity: 'Estate.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Estate sale management & appraisal services, estate planners & lawyers, real estate agents & brokers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/estate.svg',
    promoImg: '/images/domains/icann/estate.svg',
  },
  {
    name: '.events',
    entity: 'Events.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Event planners, sports & gaming agencies/sites, ticket sale/resale sites, city guides & community centers, performance halls, music clubs/bars.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.events',
    logo: '/images/domains/icann/events.svg',
    promoImg: '/images/domains/icann/events.svg',
  },
  {
    name: '.exchange',
    entity: 'Exchange.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Foreign currency exchanges, stock brokers, investment fund traders, ETF distributors, brokers, & dealers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.exchange',
    logo: '/images/domains/icann/exchange.svg',
    promoImg: '/images/domains/icann/exchange.svg',
  },
  {
    name: '.expert',
    entity: 'Expert.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Home services providers, online review sites, skilled worker databases, freelancers, consultants, & subject matter experts.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/expert.svg',
    promoImg: '/images/domains/icann/expert.svg',
  },
  {
    name: '.exposed',
    entity: 'Exposed.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Tabloid sites, celebrity romance blog, TV spoiler sites, sites that host leaked documents, investigative journalism sites.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.exposed',
    logo: '/images/domains/icann/exposed.svg',
    promoImg: '/images/domains/icann/exposed.svg',
  },
  {
    name: '.express',
    entity: 'Express.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Transportation services, messenger services, delivery & shipping services, direct-to-consumer stores.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/express.svg',
    promoImg: '/images/domains/icann/express.svg',
  },
]


export default data;
