const data = [
  {
    name: '.hair',
    entity: 'Hair.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'XYZ.com.',
      link: '',
    },
    notes: [`Haircare products and services.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hair.svg',
    promoImg: '/images/domains/icann/hair.svg',
  },
  {
    name: '.hangout',
    entity: 'Hangout.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google).',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`Reserved for Google Hangouts.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hangout.svg',
    promoImg: '/images/domains/icann/hangout.svg',
  },
  {
    name: '.hamburg',
    entity: '',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Hamburg Top-Level-Domain GmbH.',
      link: '',
    },
    notes: [
      `Companies, organizations and private individuals with a connection to the Free and Hanseatic City of Hamburg.`,
      `Unrestricted for inhabitants of Hamburg.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hamburg.svg',
    promoImg: '/images/domains/icann/hamburg.svg',
  },
  {
    name: '.haus',
    entity: 'Haus.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [`German housing and real estate.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/haus.svg',
    promoImg: '/images/domains/icann/haus.svg',
  },
  {
    name: '.health',
    entity: 'Health.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'DotHealth, LLC.',
      link: '',
    },
    notes: [`Health and related topics.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/health.svg',
    promoImg: '/images/domains/icann/health.svg',
  },
  {
    name: '.healthcare',
    entity: 'Healthcare.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Primary/secondary care physicians, hospitals & clinics, healthcare insurance providers & brokers, company HR/benefits departments.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/healthcare.svg',
    promoImg: '/images/domains/icann/healthcare.svg',
  },
  {
    name: '.help',
    entity: 'Help.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Uniregistry.',
      link: 'https://en.wikipedia.org/wiki/Uniregistry',
    },
    notes: [`Help sites.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.help',
    logo: '/images/domains/icann/help.svg',
    promoImg: '/images/domains/icann/help.svg',
  },
  {
    name: '.here',
    entity: 'Here.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google).',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`Generic geographic.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/here.svg',
    promoImg: '/images/domains/icann/here.svg',
  },
  {
    name: '.hiphop',
    entity: 'Hip-hop.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Dot Hip Hop, LLC.',
      link: 'https://en.wikipedia.org/w/index.php?title=Dot_Hip_Hop,_LLC&action=edit&redlink=1',
    },
    notes: [`Hip hop culture.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hiphop.svg',
    promoImg: '/images/domains/icann/hiphop.svg',
  },
  {
    name: '.hiv',
    entity: 'H.I.V.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'dotHIV.',
      link: '',
    },
    notes: [
      `AIDS and HIV awareness.`,
      `H.I.V - human immunodeficiency viruses.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.hiv',
    logo: '/images/domains/icann/hiv.svg',
    promoImg: '/images/domains/icann/hiv.svg',
  },
  {
    name: '.hockey',
    entity: 'Hockey.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Sports media, sporting goods stores & hockey equipment suppliers, professional, minor league & amateur hockey teams, hockey fans, fantasy leagues, sponsors, coaches & referees.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hockey.svg',
    promoImg: '/images/domains/icann/hockey.svg',
  },
  {
    name: '.holdings',
    entity: 'Holdings.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [`Holding companies, private equity firms, real estate developers.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.holdings',
    logo: '/images/domains/icann/holdings.svg',
    promoImg: '/images/domains/icann/holdings.svg',
  },
  {
    name: '.holiday',
    entity: 'Holiday.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Airline-related products or services, travel agencies, resources & services, travel writers & bloggers, city guides & resource sites, hotels, hostels, B&Bs, lodging.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/holiday.svg',
    promoImg: '/images/domains/icann/holiday.svg',
  },
  {
    name: '.homegoods',
    entity: 'Home Goods.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'The TJX Companies, Inc.',
      link: '',
    },
    notes: [`Reserved for HomeGoods.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/homegoods.svg',
    promoImg: '/images/domains/icann/homegoods.svg',
  },
  {
    name: '.homes',
    entity: 'Homes.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Dominion Enterprises.',
      link: 'https://en.wikipedia.org/wiki/Dominion_Enterprises',
    },
    notes: [`Real estate professionals.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/homes.svg',
    promoImg: '/images/domains/icann/homes.svg',
  },
  {
    name: '.horse',
    entity: 'Horse.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Minds + Machines.',
      link: '',
    },
    notes: [`Horse-related businesses and interest.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/horse.svg',
    promoImg: '/images/domains/icann/horse.svg',
  },
  {
    name: '.hospital',
    entity: 'Hospitals.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Hospitals & clinics, healthcare providers, medical, dental, or vision specialists, insurance providers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hospital.svg',
    promoImg: '/images/domains/icann/hospital.svg',
  },
  {
    name: 'host',
    entity: 'Network.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Radix Registry.',
      link: 'https://en.wikipedia.org/w/index.php?title=Radix_Registry&action=edit&redlink=1',
    },
    notes: [`Network companies.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/host.svg',
    promoImg: '/images/domains/icann/host.svg',
  },
  {
    name: '.hosting',
    entity: 'Hosting.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Uniregistry.',
      link: 'https://en.wikipedia.org/wiki/Uniregistry',
    },
    notes: [`Hostings.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hosting.svg',
    promoImg: '/images/domains/icann/hosting.svg',
  },
  {
    name: '.hot',
    entity: 'Hot.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Amazon Registry Services, Inc.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hot.svg',
    promoImg: '/images/domains/icann/hot.svg',
  },
  {
    name: '.hotels',
    entity: 'Hotels.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Booking.com B.V.',
      link: '',
    },
    notes: [`Reserved for Booking.com.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/hotels.svg',
    promoImg: '/images/domains/icann/hotels.svg',
  },
  {
    name: '.house',
    entity: 'House.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Real estate brokers/agents, mortgage companies, home builders, construction/home improvement suppliers, home improvement sites & blogs.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.house',
    logo: '/images/domains/icann/house.svg',
    promoImg: '/images/domains/icann/house.svg',
  },
  {
    name: '.how',
    entity: 'How.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`How-to guides.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/how.svg',
    promoImg: '/images/domains/icann/how.svg',
  },
]

export default data
