const data = [
  {
    name: '.yachts',
    entity: 'Yachts.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'DERYachts, LLC.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/yachts.svg',
    promoImg: '/images/domains/icann/yachts.svg',
  },
  {
    name: '.yoga',
    entity: 'Yoga.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Minds + Machines.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/yoga.svg',
    promoImg: '/images/domains/icann/yoga.svg',
  },
  {
    name: '.you',
    entity: 'You.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Amazon Registry Services, Inc.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/you.svg',
    promoImg: '/images/domains/icann/you.svg',
  },
  {
    name: '.youtube',
    entity: 'YouTube.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Google, LLC.',
      link: 'https://en.wikipedia.org/wiki/.google',
    },
    notes: [`Reserved for YouTube.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/youtube.svg',
    promoImg: '/images/domains/icann/youtube.svg',
  },
  
]

export default data
