const data = [
  {
    name: '.kim',
    entity: 'Kim.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [`Kim (Korean surname).`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/kim.svg',
    promoImg: '/images/domains/icann/kim.svg',
  },
  {
    name: '',
    entity: '',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/.svg',
    promoImg: '/images/domains/icann/.svg',
  },
  {
    name: '.kitchen',
    entity: 'Kitchen.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Restaurants, cafes, & delis, food stands & mobile vendors, meal services & personal chefs, kitchen supply stores, food blogs & recipe sites.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/kitchen.svg',
    promoImg: '/images/domains/icann/kitchen.svg',
  },
  {
    name: '.kosher',
    entity: 'Kosher.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'OK Kosher Certification.',
      link: 'https://en.wikipedia.org/wiki/OK_Kosher_Certification',
    },
    notes: [`Kosher food certification and regulations.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.kosher',
    logo: '/images/domains/icann/kosher.svg',
    promoImg: '/images/domains/icann/kosher.svg',
  },
  {
    name: '.kpn',
    entity: 'KPN.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'KPN',
      link: '',
    },
    notes: [`Dutch Telecom Company.`, `Only available to KPN.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/kpn.svg',
    promoImg: '/images/domains/icann/kpn.svg',
  },
]

export default data
