const data = [
  {
    name: '.racing',
    entity: 'Racing.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Global Registry Services Ltd.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.racing',
    logo: '/images/domains/icann/racing.svg',
    promoImg: '/images/domains/icann/racing.svg',
  },
  {
    name: '.radio',
    entity: 'Radio.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'European Broadcasting Union (EBU).',
      link: '',
    },
    notes: [`Radio stations, amateur radio operators.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.radio',
    logo: '/images/domains/icann/radio.svg',
    promoImg: '/images/domains/icann/radio.svg',
  },
  {
    name: '.read',
    entity: 'Read.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Amazon Registry Services, Inc.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/read.svg',
    promoImg: '/images/domains/icann/read.svg',
  },
  {
    name: '.realestate',
    entity: 'Reale state.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'dotRealEstate LLC.',
      link: '',
    },
    notes: [`Reale state.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/realestate.svg',
    promoImg: '/images/domains/icann/realestate.svg',
  },
  {
    name: '.realtor',
    entity: 'Realtors.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Real Estate Domains.',
      link: '',
    },
    notes: [
      `To be restricted to members of the National Association of Realtors and the Canadian Real Estate Association, and related associations.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.realtor',
    logo: '/images/domains/icann/realtor.svg',
    promoImg: '/images/domains/icann/realtor.svg',
  },
  {
    name: '.realty',
    entity: 'Realty.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Fegistry, LLC.',
      link: '',
    },
    notes: [`Realty and housing.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/realty.svg',
    promoImg: '/images/domains/icann/realty.svg',
  },
  {
    name: '.recipes',
    entity: 'Recipes.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Recipe sites, food & beverage grocery brands, health & fitness organizations, cooking enthusiasts, personal/professional chefs.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/recipes.svg',
    promoImg: '/images/domains/icann/recipes.svg',
  },
  {
    name: '.red',
    entity: 'Red.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Those who like the color red.`,
      `Also Spanish variant of .net.`,
      `Also likely to be attractive for domain hacks for words that end with '-red'.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/red.svg',
    promoImg: '/images/domains/icann/red.svg',
  },
  {
    name: '.rehab',
    entity: 'Rehab.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Physical and occupational therapists and professionals, drug, alcohol and gambling addiction counselors, rehabilitation facilities and recovery centers, online health directories, physical or emotional health associations.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/rehab.svg',
    promoImg: '/images/domains/icann/rehab.svg',
  },
  {
    name: '.reit',
    entity: 'Reit.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'National Association of Real Estate Investment Trusts.',
      link: 'https://en.wikipedia.org/wiki/National_Association_of_Real_Estate_Investment_Trusts',
    },
    notes: [
      `Real estate investment trusts.`,
      `Restricted to REITs, as determined by national law.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/reit.svg',
    promoImg: '/images/domains/icann/reit.svg',
  },
  {
    name: '.rent',
    entity: 'Rent.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'XYZ COM.',
      link: '',
    },
    notes: [`Real estate professionals and small businesses.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/rent.svg',
    promoImg: '/images/domains/icann/rent.svg',
  },
  {
    name: '.rentals',
    entity: 'Rentals.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Real estate brokers/agents, city guides, college housing centers, & community centers, vehicle, equipment, or entertainment/event rentals, property managers, condo/apartment developers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/rentals.svg',
    promoImg: '/images/domains/icann/rentals.svg',
  },
  {
    name: '.repair',
    entity: 'Repair.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `General or specialty repair shops, construction contractors/subcontractors, DIYers, appliance wholesalers & service, auto/boat businesses.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/repair.svg',
    promoImg: '/images/domains/icann/repair.svg',
  },
  {
    name: '.report',
    entity: 'Report.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `News and current events sites, financial reporting sites, financial or business analysts, consumer product reviews, police, school, or other community report listings.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/report.svg',
    promoImg: '/images/domains/icann/report.svg',
  },
  {
    name: '.republican',
    entity: 'Republican.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Political candidates, lobbyists, political parties, fundraising organizations.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/republican.svg',
    promoImg: '/images/domains/icann/republican.svg',
  },
  {
    name: '.rest',
    entity: 'Rest.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Punto 2012.',
      link: '',
    },
    notes: [`Restaurants and related industry.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/rest.svg',
    promoImg: '/images/domains/icann/rest.svg',
  },
  {
    name: '.restaurant',
    entity: 'Restaurant.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Casual eateries, gourmet restaurants, suppliers, chains, review sites, reservation sites & services.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/restaurant.svg',
    promoImg: '/images/domains/icann/restaurant.svg',
  },
  {
    name: '.review',
    entity: 'Review.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Global Registry Services Ltd',
      link: 'https://en.wikipedia.org/wiki/GRS_Domains',
    },
    notes: [`Public reviews.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.review',
    logo: '/images/domains/icann/review.svg',
    promoImg: '/images/domains/icann/review.svg',
  },
  {
    name: '.reviews',
    entity: 'Reviews.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `News media, food publications, travel publications, literary publications, any product & service with online reviews.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/reviews.svg',
    promoImg: '/images/domains/icann/reviews.svg',
  },
  {
    name: '.rich',
    entity: 'Rich.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'I-REGISTRY',
      link: '',
    },
    notes: [`Businesses catering to the wealthy.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.rich',
    logo: '/images/domains/icann/rich.svg',
    promoImg: '/images/domains/icann/rich.svg',
  },
  {
    name: '.rip',
    entity: 'Rip.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Loved ones seeking to memorialize the deceased, funeral homes and cemeteries, businesses that support the funeral industry, obituary websites.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/rip.svg',
    promoImg: '/images/domains/icann/rip.svg',
  },
  {
    name: '.rocks',
    entity: 'Rocks.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Pop culture sites, niche and fan sites, musicians, gemstone & jewelry companies.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.rocks',
    logo: '/images/domains/icann/rocks.svg',
    promoImg: '/images/domains/icann/rocks.svg',
  },
  {
    name: '.rodeo',
    entity: 'Rodeo.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Minds + Machines.',
      link: '',
    },
    notes: [`Rodeo interest.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/rodeo.svg',
    promoImg: '/images/domains/icann/rodeo.svg',
  },
  {
    name: '.room',
    entity: 'Room.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Amazon Registry Services, Inc.',
      link: '',
    },
    notes: [`Lodging or room design.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.room',
    logo: '/images/domains/icann/room.svg',
    promoImg: '/images/domains/icann/room.svg',
  },
  {
    name: '.rugby',
    entity: 'Rugby.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'World Rugby Strategic Developments Limited.',
      link: '',
    },
    notes: [`Rugby.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/rugby.svg',
    promoImg: '/images/domains/icann/rugby.svg',
  },
  {
    name: '.run',
    entity: 'Run.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Runners, running shoe retailers, specialty running gear shops, running event organizers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/run.svg',
    promoImg: '/images/domains/icann/run.svg',
  },
]

export default data
