const data = [
  {
    name: '.observer',
    entity: 'Observer.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Donuts Inc.',
      link: 'https://en.wikipedia.org/wiki/Donuts_(company)',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/observer.svg',
    promoImg: '/images/domains/icann/observer.svg',
  },
  {
    name: '.org',
    entity: 'Organisation.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Public Interest Registry.',
      link: 'https://en.wikipedia.org/wiki/Public_Interest_Registry',
    },
    notes: [`General.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.org',
    logo: '/images/domains/icann/org.svg',
    promoImg: '/images/domains/icann/org.svg',
  },
  {
    name: '.one',
    entity: 'One.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'One Registry',
      link: '',
    },
    notes: [`General.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.one_(domain)',
    logo: '/images/domains/icann/one.svg',
    promoImg: '/images/domains/icann/one.svg',
  },
  {
    name: '.ong',
    entity: 'Ong.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Public Interest Registry (PIR).',
      link: 'https://en.wikipedia.org/wiki/Public_Interest_Registry',
    },
    notes: [
      `Non-governmental organizations.`,
      `Restricted to validated NGOs, as determined by PIR.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.ngo_and_.ong',
    logo: '/images/domains/icann/ong.svg',
    promoImg: '/images/domains/icann/ong.svg',
  },
  {
    name: '.onl',
    entity: 'Onl.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'I-REGISTRY',
      link: '',
    },
    notes: [`Generic.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.onl',
    logo: '/images/domains/icann/onl.svg',
    promoImg: '/images/domains/icann/onl.svg',
  },
  {
    name: '.online',
    entity: 'Online.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Radix Registry.',
      link: '',
    },
    notes: [`Generic.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.online',
    logo: '/images/domains/icann/online.svg',
    promoImg: '/images/domains/icann/online.svg',
  },
  {
    name: '.ooo',
    entity: 'OOO.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Infibeam.',
      link: 'https://en.wikipedia.org/wiki/Infibeam',
    },
    notes: [`General.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.OOO',
    logo: '/images/domains/icann/ooo.svg',
    promoImg: '/images/domains/icann/ooo.svg',
  },
  {
    name: '.open',
    entity: 'Open.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'American Express Travel Related Services Company, Inc.',
      link: '',
    },
    notes: [
      `Private to the "Registry Operator and its qualified Affiliates and Trademark Licensees".`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.open',
    logo: '/images/domains/icann/open.svg',
    promoImg: '/images/domains/icann/open.svg',
  },
  {
    name: '.organic',
    entity: 'Organic.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Organic gardeners, farmers, foods, etc.`,
      `Registrants must be verified as a member of the organic community.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.organic',
    logo: '/images/domains/icann/organic.svg',
    promoImg: '/images/domains/icann/organic.svg',
  },
  {
    name: '.origins',
    entity: 'Origins.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'The Estée Lauder Companies Inc.',
      link: 'The Estée Lauder Companies Inc.',
    },
    notes: [`Reserved for Origins.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/origins.svg',
    promoImg: '/images/domains/icann/origins.svg',
  },
  
]

export default data
