const data = [
  {
    name: '.ice',
    entity: 'Ice.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'IntercontinentalExchange, Inc.',
      link: '',
    },
    notes: [`Reserved for Intercontinental Exchange.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/ice.svg',
    promoImg: '/images/domains/icann/ice.svg',
  },
  {
    name: '.icu',
    entity: 'Icu.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'ShortDot SA.',
      link: '',
    },
    notes: [`Entrepreneurs and business owners.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/icu.svg',
    promoImg: '/images/domains/icann/icu.svg',
  },
  {
    name: '.inc',
    entity: 'Corporations.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Intercap Registry Inc.',
      link: '',
    },
    notes: [`Corporations.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.inc',
    logo: '/images/domains/icann/inc.svg',
    promoImg: '/images/domains/icann/inc.svg',
  },
  {
    name: '.industries',
    entity: 'Industries.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Machine or equipment manufacturers, manufacturers, tech or biotech companies, professional associations, businesses with “industries” in their names.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/industries.svg',
    promoImg: '/images/domains/icann/industries.svg',
  },
  {
    name: '.info',
    entity: 'Information.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [`Information.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/info.svg',
    promoImg: '/images/domains/icann/info.svg',
  },
  {
    name: '.ing',
    entity: 'jump.ing',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`Verbal suffix: e.g., "jump.ing".`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/ing.svg',
    promoImg: '/images/domains/icann/ing.svg',
  },
  {
    name: '.ink',
    entity: 'Ink.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Top Level Design.',
      link: 'https://en.wikipedia.org/wiki/Top_Level_Design',
    },
    notes: [`Creative printing or tattooing.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/ink.svg',
    promoImg: '/images/domains/icann/ink.svg',
  },
  {
    name: '.institute',
    entity: 'Institute.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Educational institutions, training programs, foundations, research organizations, military schools.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/institute.svg',
    promoImg: '/images/domains/icann/institute.svg',
  },
  {
    name: '.insurance',
    entity: 'Insurance.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'fTLD Registry Services LLC.',
      link: '',
    },
    notes: [`Insurance companies.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/insurance.svg',
    promoImg: '/images/domains/icann/insurance.svg',
  },
  {
    name: '.insure',
    entity: 'Insure.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Insurance companies (life, auto, homeowners, renters), insurance divisions of larger companies (car rentals, warranties), insurance brokers & advisors.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/insure.svg',
    promoImg: '/images/domains/icann/insure.svg',
  },
  {
    name: '.international',
    entity: 'International.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Any organization with an international presence, international consultants, import/export businesses, international travel organizations.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/international.svg',
    promoImg: '/images/domains/icann/international.svg',
  },
  {
    name: '.investments',
    entity: 'Investments.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Investment services (institutional, private), wealth management services, financial planners, brokerage firms.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/investments.svg',
    promoImg: '/images/domains/icann/investments.svg',
  },
  {
    name: '.irish',
    entity: 'Irish.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Airline-related products or services, domestic/International travel agencies, resources & services, travel writers & bloggers, Ireland travel guides & resource sites, seasonal opportunities (St. Patrick's Day).`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.irish',
    logo: '/images/domains/icann/irish.svg',
    promoImg: '/images/domains/icann/irish.svg',
  },
]

export default data
