const data = [
  {
    name: '.makeup',
    entity: 'Makeup.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'XYZ.com.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/makeup.svg',
    promoImg: '/images/domains/icann/makeup.svg',
  },
  {
    name: '.management',
    entity: 'Management.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Property managers, wealth management firms, money management, systems & network managers, leadership teams.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/management.svg',
    promoImg: '/images/domains/icann/management.svg',
  },
  {
    name: '.map',
    entity: 'Navigation.',
    sponsor: {
      title: 'Charleston Road Registry Inc. (Google).',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Maps and navigation.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/map.svg',
    promoImg: '/images/domains/icann/map.svg',
  },
  {
    name: '.market',
    entity: 'Market.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Online retailers, independent or chain grocery stores, buyer and seller communities, discount sites & coupon sites.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.market',
    logo: '/images/domains/icann/market.svg',
    promoImg: '/images/domains/icann/market.svg',
  },
  {
    name: '.marketing',
    entity: 'Marketing.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Advertising/Marketing/PR/Design agencies, media buying/production companies (digital & traditional), staffing agencies, marketing consultants.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/marketing.svg',
    promoImg: '/images/domains/icann/marketing.svg',
  },
  {
    name: '.markets',
    entity: 'Markets.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Donuts',
      link: 'https://en.wikipedia.org/wiki/Donuts_(company)',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/markets.svg',
    promoImg: '/images/domains/icann/markets.svg',
  },
  {
    name: '.mba',
    entity: 'Mba.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Colleges, universities, & graduate programs, online educational sites, job search sites, MBA candidates.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/mba.svg',
    promoImg: '/images/domains/icann/mba.svg',
  },
  {
    name: '.med',
    entity: 'Med.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Medistry LLC.',
      link: '',
    },
    notes: [`Medicine and related topics.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.med',
    logo: '/images/domains/icann/med.svg',
    promoImg: '/images/domains/icann/med.svg',
  },
  {
    name: '.media',
    entity: 'Media.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Advertising/Marketing/PR/Design agencies, media buying/production companies (digital & traditional), news outlets, media bloggers, celebrity publications, digital publishers & graphic designers.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/media.svg',
    promoImg: '/images/domains/icann/media.svg',
  },
  {
    name: '.meet',
    entity: 'Meet.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [`Social gatherings, meeting new people.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Google_Registry',
    logo: '/images/domains/icann/meet.svg',
    promoImg: '/images/domains/icann/meet.svg',
  },
  {
    name: '.meme',
    entity: 'Meme.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google)',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`Internet memes.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/meme.svg',
    promoImg: '/images/domains/icann/meme.svg',
  },
  {
    name: '.memorial',
    entity: 'Memorial.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `News site obituaries, personal tribute sites, floral & funeral arrangement companies.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/memorial.svg',
    promoImg: '/images/domains/icann/memorial.svg',
  },
  {
    name: '.men',
    entity: 'Men.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Global Registry Services Ltd',
      link: '',
    },
    notes: [`For mens.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/men.svg',
    promoImg: '/images/domains/icann/men.svg',
  },
  {
    name: '.menu',
    entity: 'Menu.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Wedding TLD2.',
      link: '',
    },
    notes: [`Restaurants.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.menu',
    logo: '/images/domains/icann/menu.svg',
    promoImg: '/images/domains/icann/menu.svg',
  },
  {
    name: '.mint',
    entity: 'Mint.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Intuit Administrative Services, Inc.',
      link: '',
    },
    notes: [`Reserved for Intuit Mint.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/mint.svg',
    promoImg: '/images/domains/icann/mint.svg',
  },
  {
    name: '.mobi',
    entity: 'Mobile.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Mobile devices.`,
      `Must be used for mobile-compatible sites in accordance with standards.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.mobi',
    logo: '/images/domains/icann/mobi.svg',
    promoImg: '/images/domains/icann/mobi.svg',
  },

  {
    name: '.mobile',
    entity: 'Mobile.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Dish DBS Corporation.',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/mobile.svg',
    promoImg: '/images/domains/icann/mobile.svg',
  },
  {
    name: '.mobily',
    entity: 'Mobily.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'GreenTech Consultancy Company W.L.L.',
      link: '',
    },
    notes: [`Reserved for Mobily.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/mobily.svg',
    promoImg: '/images/domains/icann/mobily.svg',
  },
  {
    name: '.moda',
    entity: 'Moda.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `For people and organizations interested and engaged in the world of fashion and style.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: ``,
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/moda.svg',
    promoImg: '/images/domains/icann/moda.svg',
  },
  {
    name: '.moe',
    entity: 'Moe.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Interlink.',
      link: '',
    },
    notes: [
      `Japanese otaku culture; see moe (slang).`,
      `Its name comes from the Japanese slang word moe, indicating its intended purpose in the marketing of products or services deemed moe.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.moe',
    logo: '/images/domains/icann/moe.svg',
    promoImg: '/images/domains/icann/moe.svg',
  },
  {
    name: 'mom',
    entity: 'Mothers.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Uniregistry, Corp.',
      link: 'https://en.wikipedia.org/wiki/Uniregistry',
    },
    notes: [`Mothers.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.mom',
    logo: '/images/domains/icann/mom.svg',
    promoImg: '/images/domains/icann/mom.svg',
  },
  {
    name: '.money',
    entity: 'Money.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Lenders, financial services businesses, money blogs & news sites, investment bankers & brokers, financial planners & experts.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/money.svg',
    promoImg: '/images/domains/icann/money.svg',
  },
  {
    name: '.monster',
    entity: 'Monster.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'XYZ.com',
      link: '',
    },
    notes: [
      `Originally delegated in 2014 by the employment website Monster.com as a brand-specific domain name.`,
      `At the launch of .monster, XYZ.com CEO Daniel Negari referred to it as a "wacky and creative" domain for users wanting to metaphorically demonstrate being "a beast at what [they] do". Multiple commentators have described the use case of .monster as unclear, with James Sanders at TechRepublic saying "the 'who is this for' question is a difficult one to answer" and Andrew Allemann of Domain Name Wire feeling the announcement "seem[ed] like a bad April Fools' Day joke".`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.monster',
    logo: '/images/domains/icann/monster.svg',
    promoImg: '/images/domains/icann/monster.svg',
  },
  {
    name: '.mortgage',
    entity: 'Mortgage.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Mortgage brokers, real estate brokers/agents, home buyers, traditional “classified” sites.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/mortgage.svg',
    promoImg: '/images/domains/icann/mortgage.svg',
  },
  {
    name: '.motorcycles',
    entity: 'Motorcycles.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'DERMotorcycles',
      link: '',
    },
    notes: [`Motorcycles.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/motorcycles.svg',
    promoImg: '/images/domains/icann/motorcycles.svg',
  },
  {
    name: '.mov',
    entity: 'Mov.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Charleston Road Registry Inc. (Google).',
      link: 'https://en.wikipedia.org/wiki/Google',
    },
    notes: [`Digital video.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/icann/mov.svg',
    promoImg: '/images/domains/icann/mov.svg',
  },
  {
    name: '.movie',
    entity: 'Movie.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Identity Digital.',
      link: 'https://en.wikipedia.org/wiki/Identity_Digital',
    },
    notes: [
      `Streaming movie services, movie studios & distributors, movie theaters & entertainment outlets, ticket sale/resale sites, movie review sites.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.movie',
    logo: '/images/domains/icann/movie.svg',
    promoImg: '/images/domains/icann/movie.svg',
  },
  {
    name: '.museum',
    entity: 'Museums.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Museum Domain Management Association.',
      link: 'https://en.wikipedia.org/wiki/Museum_Domain_Management_Association',
    },
    notes: [`Must be verified as a legitimate museum.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.museum',
    logo: '/images/domains/icann/museum.svg',
    promoImg: '/images/domains/icann/museum.svg',
  },
  {
    name: '.music',
    entity: 'Music.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'DotMusic Limited.',
      link: '',
    },
    notes: [`Music dissemination and appreciation.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.music',
    logo: '/images/domains/icann/music.svg',
    promoImg: '/images/domains/icann/music.svg',
  },

]

export default data
