const data = [
  {
    name: '.abudhabi',
    entity: 'Abu Dhabi.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Abu Dhabi, UAE`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Emirate_of_Abu_Dhabi',
    logo: '/images/domains/geoTLD/abudhabi.svg',
    promoImg: '/images/domains/geoTLD/abudhabi.svg',
  },
  {
    name: '.arab',
    entity: 'Arab States.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`League of Arab States`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Arab_League',
    logo: '/images/domains/geoTLD/arab.svg',
    promoImg: '/images/domains/geoTLD/arab.svg',
  },
  {
    name: '.asia',
    entity: 'Asia–Pacific.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [
      `Asia–Pacific region.`,
      `This is a TLD for companies, organizations, and individuals based in the region of Asia, Australia, and the Pacific.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.asia',
    logo: '/images/domains/geoTLD/asia.svg',
    promoImg: '/images/domains/geoTLD/asia.svg',
  },
  {
    name: '.doha',
    entity: 'Doha.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Doha, Qatar.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Doha',
    logo: '/images/domains/geoTLD/doha.svg',
    promoImg: '/images/domains/geoTLD/doha.svg',
  },
  {
    name: '.dubai',
    entity: 'Dubai.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Dubai, UAE.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Dubai',
    logo: '/images/domains/geoTLD/dubai.svg',
    promoImg: '/images/domains/geoTLD/dubai.svg',
  },
  {
    name: '.krd',
    entity: 'Kurdistan.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [
      `This is a TLD for companies, organizations, and individuals based in the region of Kurdistan.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Kurdistan_Region',
    logo: '/images/domains/geoTLD/krd.svg',
    promoImg: '/images/domains/geoTLD/krd.svg',
  },
  {
    name: '.kyoto',
    entity: 'Kyoto.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Kyoto, Japan.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Kyoto_Prefecture',
    logo: '/images/domains/geoTLD/kyoto.svg',
    promoImg: '/images/domains/geoTLD/kyoto.svg',
  },
  {
    name: '.nagoya',
    entity: 'Nagoya.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Nagoya, Japan.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Nagoya',
    logo: '/images/domains/geoTLD/nagoya.svg',
    promoImg: '/images/domains/geoTLD/nagoya.svg',
  },
  {
    name: '.okinawa',
    entity: 'Okinawa.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Okinawa, Japan.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Okinawa_Prefecture',
    logo: '/images/domains/geoTLD/okinawa.svg',
    promoImg: '/images/domains/geoTLD/okinawa.svg',
  },
  {
    name: '.osaka',
    entity: 'Osaka.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Osaka, Japan.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Osaka_Prefecture',
    logo: '/images/domains/geoTLD/osaka.svg',
    promoImg: '/images/domains/geoTLD/osaka.svg',
  },
  {
    name: '.ryukyu',
    entity: 'Ryukyu.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Ryukyu Islands, Japan.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Ryukyu_Islands',
    logo: '/images/domains/geoTLD/ryukyu.svg',
    promoImg: '/images/domains/geoTLD/ryukyu.svg',
  },
  {
    name: '.taipei',
    entity: 'Taipei.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Taipei, Taiwan.`, `Introduced in September 2014.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.taipei',
    logo: '/images/domains/geoTLD/taipei.svg',
    promoImg: '/images/domains/geoTLD/taipei.svg',
  },
  {
    name: '.tokyo',
    entity: 'Tokyo.',
    sponsor: {
      title: 'Metropolis of Tokyo.',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Tokyo, Japan.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.tokyo',
    logo: '/images/domains/geoTLD/tokyo.svg',
    promoImg: '/images/domains/geoTLD/tokyo.svg',
  },
  {
    name: '.yokohama',
    entity: 'Yokohama.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Yokohama, Japan.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Yokohama',
    logo: '/images/domains/geoTLD/yokohama.svg',
    promoImg: '/images/domains/geoTLD/yokohama.svg',
  },
  
]

export default data
