const data = [
  {
    name: '.africa',
    entity: 'Africa.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.africa',
    logo: '/images/domains/geoTLD/africa.svg',
    promoImg: '/images/domains/geoTLD/africa.svg',
  },
  {
    name: '.capetown',
    entity: 'Cape Town.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Cape Town, South Africa`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Cape_Town',
    logo: '/images/domains/geoTLD/capetown.svg',
    promoImg: '/images/domains/geoTLD/capetown.svg',
  },
  {
    name: '.durban',
    entity: 'Durban.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Durban, South Africa.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Durban',
    logo: '/images/domains/geoTLD/durban.svg',
    promoImg: '/images/domains/geoTLD/durban.svg',
  },
  {
    name: '.joburg',
    entity: 'Johannesburg.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Johannesburg, South Africa.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Johannesburg',
    logo: '/images/domains/geoTLD/joburg.svg',
    promoImg: '/images/domains/geoTLD/joburg.svg',
  },
]


export default data;
