const data = [
  {
    name: '.bcn',
    entity: 'Barcelona.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [
      `According to the Barcelona City Council, the .bcn domain is intended to maintain a relationship of "cooperation and sum of efforts" with the .cat domain, even though the proposal has already received the criticisms of the Generalitat de Catalunya[2][3] and of several personalities from the cultural and technological world of Catalonia.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.bcn',
    logo: '/images/domains/geoTLD/bcn.svg',
    promoImg: '/images/domains/geoTLD/bcn.svg',
  },
  {
    name: '.barcelona',
    entity: 'Barcelona.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [
      `According to the Barcelona City Council, the .bcn domain is intended to maintain a relationship of "cooperation and sum of efforts" with the .cat domain, even though the proposal has already received the criticisms of the Generalitat de Catalunya[2][3] and of several personalities from the cultural and technological world of Catalonia.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.bcn',
    logo: '/images/domains/geoTLD/barcelona.svg',
    promoImg: '/images/domains/geoTLD/barcelona.svg',
  },
  {
    name: '.cat',
    entity: 'Catalonia.',
    sponsor: {
      title: 'Fundació puntCat.',
      link: 'https://en.wikipedia.org/wiki/Fundaci%C3%B3_puntCat',
    },
    administrator: {
      title: 'Associació puntCAT.',
      link: '/',
    },
    notes: [
      `This is a TLD for Web sites in the Catalan language or related to Catalan culture.`,
    ],
    defaultPrice: 0,
    introduced: '	December 19, 2005',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.cat',
    logo: '/images/domains/geoTLD/cat.svg',
    promoImg: '/images/domains/geoTLD/cat.svg',
  },
  {
    name: '.eus',
    entity: 'EUS.',
    sponsor: {
      title: 'PuntuEus Fundazioa.',
      link: '',
    },
    administrator: {
      title: 'Domeinuak.',
      link: '/',
    },
    notes: [`Basque, Spain and France.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.eus',
    logo: '/images/domains/geoTLD/eus.svg',
    promoImg: '/images/domains/geoTLD/eus.svg',
  },
  {
    name: '.gal',
    entity: 'Galicia.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [
      `This is a TLD for Web sites in the Galician language or related to Galician culture.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.gal',
    logo: '/images/domains/geoTLD/gal.svg',
    promoImg: '/images/domains/geoTLD/gal.svg',
  },

  {
    name: '.madrid',
    entity: 'Madrid.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Madrid.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Community_of_Madrid',
    logo: '/images/domains/geoTLD/madrid.svg',
    promoImg: '/images/domains/geoTLD/madrid.svg',
  },
  
]

export default data
