const data = [
  {
    name: '.eu',
    entity: 'EU.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [
      `EU - European Union.`,
      `Available for any person, company or organization based in the European Union.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.eu',
    logo: '/images/domains/geoTLD/eu.svg',
    promoImg: '/images/domains/geoTLD/eu.svg',
  },
  {
    name: '.amsterdam',
    entity: 'Amsterdam.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'ICANN.',
      link: '/',
    },
    notes: [`Amsterdam, Netherlands.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.amsterdam',
    logo: '/images/domains/geoTLD/amsterdam.svg',
    promoImg: '/images/domains/geoTLD/amsterdam.svg',
  },
  {
    name: '.bar',
    entity: 'Montenegro.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [
      `Bar, Montenegro.`,
      `Mostly used for bars and other alcohol facilities worldwide.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.bar',
    logo: '/images/domains/geoTLD/bar.svg',
    promoImg: '/images/domains/geoTLD/bar.svg',
  },
  {
    name: '.brussels',
    entity: 'Brussels.',
    sponsor: {
      title: 'DNS Belgium vzw/asbl',
      link: '',
    },
    administrator: {
      title: 'DNS Belgium.',
      link: 'https://en.wikipedia.org/wiki/DNS_Belgium',
    },
    notes: [`Brussels, Belgium.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.brussels',
    logo: '/images/domains/geoTLD/brussels.svg',
    promoImg: '/images/domains/geoTLD/brussels.svg',
  },
  {
    name: '.cymru',
    entity: 'Cymru.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Wales, United Kingdom.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.cymru',
    logo: '/images/domains/geoTLD/cymru.svg',
    promoImg: '/images/domains/geoTLD/cymru.svg',
  },
  {
    name: '.wales',
    entity: 'Wales.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Wales, United Kingdom.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.wales',
    logo: '/images/domains/geoTLD/wales.svg',
    promoImg: '/images/domains/geoTLD/wales.svg',
  },
  {
    name: '.frl',
    entity: 'Friesland.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'FRLregistry B.V.',
      link: '/',
    },
    notes: [
      `Friesland, Netherlands.`,
      `Fryslân in (West) Frisian, one of the twelve provinces in the Netherlands.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.frl',
    logo: '/images/domains/geoTLD/frl.svg',
    promoImg: '/images/domains/geoTLD/frl.svg',
  },
  {
    name: '.gent',
    entity: 'Gent.',
    sponsor: {
      title: 'Combell.',
      link: '',
    },
    administrator: {
      title: 'Dot Gent Registry',
      link: '/',
    },
    notes: [`Ghent, Belgium.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.gent',
    logo: '/images/domains/geoTLD/gent.svg',
    promoImg: '/images/domains/geoTLD/gent.svg',
  },
  {
    name: '.helsinki',
    entity: 'Helsinki.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Helsinki, Finland.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Helsinki',
    logo: '/images/domains/geoTLD/helsinki.svg',
    promoImg: '/images/domains/geoTLD/helsinki.svg',
  },
  {
    name: '.irish',
    entity: 'Ireland.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Ireland; global Irish community.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.irish',
    logo: '/images/domains/geoTLD/irish.svg',
    promoImg: '/images/domains/geoTLD/irish.svg',
  },
  {
    name: '.ist',
    entity: 'Istanbul.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`İstanbul, Turkey.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.istanbul',
    logo: '/images/domains/geoTLD/ist.svg',
    promoImg: '/images/domains/geoTLD/ist.svg',
  },
  {
    name: '.istanbul',
    entity: 'Istanbul.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`İstanbul, Turkey.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.istanbul',
    logo: '/images/domains/geoTLD/istanbul.svg',
    promoImg: '/images/domains/geoTLD/istanbul.svg',
  },
  {
    name: '.london',
    entity: 'London.',
    sponsor: {
      title: 'London.',
      link: '',
    },
    administrator: {
      title: 'Minds + Machines Group Limited.',
      link: '/',
    },
    notes: [`London, United Kingdom.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.london',
    logo: '/images/domains/geoTLD/london.svg',
    promoImg: '/images/domains/geoTLD/london.svg',
  },
  {
    name: '.moscow',
    entity: 'Moscow.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Moscow, Russia.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.moscow',
    logo: '/images/domains/geoTLD/moscow.svg',
    promoImg: '/images/domains/geoTLD/moscow.svg',
  },
  {
    name: '.scot',
    entity: 'Scotland.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Scotland, United Kingdom.`],
    defaultPrice: 0,
    introduced: '15 July 2014.',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.scot',
    logo: '/images/domains/geoTLD/scot.svg',
    promoImg: '/images/domains/geoTLD/scot.svg',
  },
  {
    name: '.st',
    entity: 'Stockholm.',
    sponsor: {
      title: 'Tecnisys.',
      link: 'https://en.wikipedia.org/wiki/Tecnisys',
    },
    administrator: {
      title: 'Bahnhof ST Registry.',
      link: 'https://en.wikipedia.org/wiki/Bahnhof',
    },
    notes: [`Stockholm, Sweden.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.st',
    logo: '/images/domains/geoTLD/st.svg',
    promoImg: '/images/domains/geoTLD/st.svg',
  },
  {
    name: '.swiss',
    entity: 'Switzerland.',
    sponsor: {
      title: 'Federal Office of Communications (OFCOM).',
      link: '',
    },
    administrator: {
      title: 'dot.swiss',
      link: '/',
    },
    notes: [
      `Switzerland.`,
      `This is meant to supplement the traditional .ch TLD.`,
    ],
    defaultPrice: 0,
    introduced: '7 September 2015.',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.swiss',
    logo: '/images/domains/geoTLD/swiss.svg',
    promoImg: '/images/domains/geoTLD/swiss.svg',
  },
  {
    name: '.tatar',
    entity: 'Tatar.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [
      `Tatar peoples and places.`,
      `Tatarstan is a region in Russia, though this TLD is meant for the global Tatar community.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/geoTLD/tatar.svg',
    promoImg: '/images/domains/geoTLD/tatar.svg',
  },
  {
    name: '.tirol',
    entity: 'Tyrol.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Tyrol, Austria.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.tirol',
    logo: '/images/domains/geoTLD/tirol.svg',
    promoImg: '/images/domains/geoTLD/tirol.svg',
  },
  {
    name: '.vlaanderen',
    entity: 'Flanders.',
    sponsor: {
      title: 'DNS Belgium.',
      link: 'https://en.wikipedia.org/wiki/DNS_Belgium',
    },
    administrator: {
      title: 'DNS Belgium.',
      link: 'https://en.wikipedia.org/wiki/DNS_Belgium',
    },
    notes: [`Flanders, Belgium.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.vlaanderen',
    logo: '/images/domains/geoTLD/vlaanderen.svg',
    promoImg: '/images/domains/geoTLD/vlaanderen.svg',
  },
  {
    name: '.wien',
    entity: 'Vienna.',
    sponsor: {
      title: 'Vienna.',
      link: '',
    },
    administrator: {
      title: 'punkt.wien.',
      link: '/',
    },
    notes: [`Vienna, Austria.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.wien',
    logo: '/images/domains/geoTLD/wien.svg',
    promoImg: '/images/domains/geoTLD/wien.svg',
  },
  {
    name: '.zuerich',
    entity: 'Zurich.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Zurich, Switzerland.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/geoTLD/zuerich.svg',
    promoImg: '/images/domains/geoTLD/zuerich.svg',
  },
  {
    name: '.su',
    entity: 'Soviet Union.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '/',
    },
    notes: [`Soviet Union.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.su',
    logo: '/images/domains/geoTLD/su.svg',
    promoImg: '/images/domains/geoTLD/su.svg',
  },

]

export default data
