const data = [
  
  {
    name: '.sydney',
    entity: 'Sydney.',
    sponsor: {
      title: '.au Domain Administration ',
      link: 'https://en.wikipedia.org/wiki/.au_Domain_Administration',
    },
    administrator: { title: 'Various', link: '/' },
    notes: [`Sydney, Australia.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.sydney',
    logo: '/images/domains/geoTLD/sydney.svg',
    promoImg: '/images/domains/geoTLD/sydney.svg',
  },
  {
    name: '.melbourne',
    entity: 'Melbourne.',
    sponsor: {
      title: '.au Domain Administration ',
      link: 'https://en.wikipedia.org/wiki/.au_Domain_Administration',
    },
    administrator: { title: 'Various', link: '/' },
    notes: [`Melbourne, Australia.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.melbourne',
    logo: '/images/domains/geoTLD/melbourne.svg',
    promoImg: '/images/domains/geoTLD/melbourne.svg',
  },
  {
    name: '.kiwi',
    entity: 'New Zealanders.',
    sponsor: {
      title: 'Dot Kiwi Ltd.',
      link: '',
    },
    administrator: {
      title: 'Dot Kiwi Ltd.',
      link: '/',
    },
    notes: [
      `.kiwi is an Internet generic top-level domain with emphasis on New Zealand. It employs the colloquial term kiwi, used to refer to New Zealanders.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: true,
    dnssec: true,
    sld: true,
    ipv6: true,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.kiwi',
    logo: '/images/domains/geoTLD/kiwi.svg',
    promoImg: '/images/domains/geoTLD/kiwi.svg',
  },
]

export default data
