const data = [
  {
    name: '.baidu',
    entity: 'Baidu.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Baidu',
    logo: '/images/domains/bTLD/baidu.svg',
    promoImg: '/images/domains/bTLD/baidu.svg',
  },
  {
    name: '.bananarepublic',
    entity: '.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Banana_Republic',
    logo: '/images/domains/bTLD/bananarepublic.svg',
    promoImg: '/images/domains/bTLD/bananarepublic.svg',
  },
  {
    name: '.barclaycard',
    entity: 'Barclays.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Barclays',
    logo: '/images/domains/bTLD/barclaycard.svg',
    promoImg: '/images/domains/bTLD/barclaycard.svg',
  },
  {
    name: '.barclays',
    entity: 'Barclays.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Barclays',
    logo: '/images/domains/bTLD/barclays.svg',
    promoImg: '/images/domains/bTLD/barclays.svg',
  },
  {
    name: '.basketball',
    entity: 'FIBA.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/FIBA',
    logo: '/images/domains/bTLD/basketball.svg',
    promoImg: '/images/domains/bTLD/basketball.svg',
  },
  {
    name: '.bauhaus',
    entity: 'Werkhaus.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Werkhaus GmbH.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/bauhaus.svg',
    promoImg: '/images/domains/bTLD/bauhaus.svg',
  },
  {
    name: '.bbc',
    entity: 'BBC.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/BBC',
    logo: '/images/domains/bTLD/bbc.svg',
    promoImg: '/images/domains/bTLD/bbc.svg',
  },
  {
    name: '.bbt',
    entity: 'BB&T.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Truist_Financial',
    logo: '/images/domains/bTLD/bbt.svg',
    promoImg: '/images/domains/bTLD/bbt.svg',
  },
  {
    name: '.bbva',
    entity: 'BBVA.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Banco_Bilbao_Vizcaya_Argentaria',
    logo: '/images/domains/bTLD/bbva.svg',
    promoImg: '/images/domains/bTLD/bbva.svg',
  },
  {
    name: '.bcg',
    entity: 'BCG.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Boston Consulting Group.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Boston_Consulting_Group',
    logo: '/images/domains/bTLD/bcg.svg',
    promoImg: '/images/domains/bTLD/bcg.svg',
  },
  {
    name: '.bentley',
    entity: 'Bentley.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bentley',
    logo: '/images/domains/bTLD/bentley.svg',
    promoImg: '/images/domains/bTLD/bentley.svg',
  },
  {
    name: '.bharti',
    entity: 'Bharti.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bharti_Enterprises',
    logo: '/images/domains/bTLD/bharti.svg',
    promoImg: '/images/domains/bTLD/bharti.svg',
  },
  {
    name: '.bing',
    entity: 'Bing.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Microsoft Bing.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Microsoft_Bing',
    logo: '/images/domains/bTLD/bing.svg',
    promoImg: '/images/domains/bTLD/bing.svg',
  },
  {
    name: '.blanco',
    entity: '.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`BLANCO GmbH + Co KG.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/blanco.svg',
    promoImg: '/images/domains/bTLD/blanco.svg',
  },
  {
    name: '.bloomberg',
    entity: 'Bloomberg.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bloomberg_L.P.',
    logo: '/images/domains/bTLD/bloomberg.svg',
    promoImg: '/images/domains/bTLD/bloomberg.svg',
  },
  {
    name: '.bms',
    entity: 'BMS.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bristol_Myers_Squibb',
    logo: '/images/domains/bTLD/bms.svg',
    promoImg: '/images/domains/bTLD/bms.svg',
  },
  {
    name: '.bmw',
    entity: 'BMW.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/BMW',
    logo: '/images/domains/bTLD/bmw.svg',
    promoImg: '/images/domains/bTLD/bmw.svg',
  },
  {
    name: '.bnl',
    entity: 'BNL.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Banca_Nazionale_del_Lavoro',
    logo: '/images/domains/bTLD/bnl.svg',
    promoImg: '/images/domains/bTLD/bnl.svg',
  },
  {
    name: '.bnpparibas',
    entity: 'BNP Parisbas.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/BNP_Paribas',
    logo: '/images/domains/bTLD/bnpparibas.svg',
    promoImg: '/images/domains/bTLD/bnpparibas.svg',
  },
  {
    name: '.boehringer',
    entity: 'Boehringer.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Boehringer_Ingelheim',
    logo: '/images/domains/bTLD/boehringer.svg',
    promoImg: '/images/domains/bTLD/boehringer.svg',
  },
  {
    name: '.bond',
    entity: 'Bond.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bond_University',
    logo: '/images/domains/bTLD/bond.svg',
    promoImg: '/images/domains/bTLD/bond.svg',
  },
  {
    name: '.booking',
    entity: 'Booking.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Booking.com',
    logo: '/images/domains/bTLD/booking.svg',
    promoImg: '/images/domains/bTLD/booking.svg',
  },
  {
    name: '.bosch',
    entity: 'Bosch.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bosch_(company)',
    logo: '/images/domains/bTLD/bosch.svg',
    promoImg: '/images/domains/bTLD/bosch.svg',
  },
  {
    name: '.bostik',
    entity: 'Bostik.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bostik',
    logo: '/images/domains/bTLD/bostik.svg',
    promoImg: '/images/domains/bTLD/bostik.svg',
  },
  {
    name: '.bradesco',
    entity: 'Bradesco.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Banco_Bradesco',
    logo: '/images/domains/bTLD/bradesco.svg',
    promoImg: '/images/domains/bTLD/bradesco.svg',
  },
  {
    name: '.bridgestone',
    entity: 'Bridgestone.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bridgestone',
    logo: '/images/domains/bTLD/bridgestone.svg',
    promoImg: '/images/domains/bTLD/bridgestone.svg',
  },
  {
    name: '.brother',
    entity: 'Brother.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Brother_Industries',
    logo: '/images/domains/bTLD/brother.svg',
    promoImg: '/images/domains/bTLD/brother.svg',
  },
  {
    name: '.bugatti',
    entity: 'Bugatti.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bugatti',
    logo: '/images/domains/bTLD/bugatti.svg',
    promoImg: '/images/domains/bTLD/bugatti.svg',
  },

]

export default data
