const data = [
  {
    name: '.ubs',
    entity: 'UBS.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/UBS',
    logo: '/images/domains/bTLD/ubs.svg',
    promoImg: '/images/domains/bTLD/ubs.svg',
  },
  {
    name: '.unicom',
    entity: 'Unicom.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/China_Unicom',
    logo: '/images/domains/bTLD/unicom.svg',
    promoImg: '/images/domains/bTLD/unicom.svg',
  },
  {
    name: '.uol',
    entity: 'UOL.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Universo_Online',
    logo: '/images/domains/bTLD/uol.svg',
    promoImg: '/images/domains/bTLD/uol.svg',
  },
  {
    name: '.ups',
    entity: 'UPS.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/United_Parcel_Service',
    logo: '/images/domains/bTLD/ups.svg',
    promoImg: '/images/domains/bTLD/ups.svg',
  },

]

export default data
