const data = [
  {
    name: '.taobao',
    entity: 'Taobao.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Taobao',
    logo: '/images/domains/bTLD/taobao.svg',
    promoImg: '/images/domains/bTLD/taobao.svg',
  },
  {
    name: '.target',
    entity: 'Target.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Target_Corporation',
    logo: '/images/domains/bTLD/target.svg',
    promoImg: '/images/domains/bTLD/target.svg',
  },
  {
    name: '.tatamotors',
    entity: 'Tata Motors.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Tata_Motors',
    logo: '/images/domains/bTLD/tatamotors.svg',
    promoImg: '/images/domains/bTLD/tatamotors.svg',
  },
  {
    name: '.tdk',
    entity: 'TDK.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/TDK',
    logo: '/images/domains/bTLD/tdk.svg',
    promoImg: '/images/domains/bTLD/tdk.svg',
  },
  {
    name: '.telecity',
    entity: 'Telecity.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/TelecityGroup',
    logo: '/images/domains/bTLD/telecity.svg',
    promoImg: '/images/domains/bTLD/telecity.svg',
  },
  {
    name: '.telefonica',
    entity: 'Telefonica.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Telef%C3%B3nica',
    logo: '/images/domains/bTLD/telefonica.svg',
    promoImg: '/images/domains/bTLD/telefonica.svg',
  },
  {
    name: '.temasek',
    entity: 'Temasek.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Temasek_(company)',
    logo: '/images/domains/bTLD/temasek.svg',
    promoImg: '/images/domains/bTLD/temasek.svg',
  },
  {
    name: '.teva',
    entity: 'Teva.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Teva_Pharmaceuticals',
    logo: '/images/domains/bTLD/teva.svg',
    promoImg: '/images/domains/bTLD/teva.svg',
  },
  {
    name: '.tiffany',
    entity: 'Tiffany.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Tiffany_%26_Co.',
    logo: '/images/domains/bTLD/tiffany.svg',
    promoImg: '/images/domains/bTLD/tiffany.svg',
  },
  {
    name: '.tjx',
    entity: 'TJX.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/TJX_Companies',
    logo: '/images/domains/bTLD/tjx.svg',
    promoImg: '/images/domains/bTLD/tjx.svg',
  },
  {
    name: '.toray',
    entity: 'Toray.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Toray_Industries',
    logo: '/images/domains/bTLD/toray.svg',
    promoImg: '/images/domains/bTLD/toray.svg',
  },
  {
    name: '.toshiba',
    entity: 'Toshiba.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Toshiba',
    logo: '/images/domains/bTLD/toshiba.svg',
    promoImg: '/images/domains/bTLD/toshiba.svg',
  },
  {
    name: '.total',
    entity: 'Total.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/TotalEnergies',
    logo: '/images/domains/bTLD/total.svg',
    promoImg: '/images/domains/bTLD/total.svg',
  },
  {
    name: '.toyota',
    entity: 'Toyota.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Toyota',
    logo: '/images/domains/bTLD/toyota.svg',
    promoImg: '/images/domains/bTLD/toyota.svg',
  },
  {
    name: '.travelchannel',
    entity: 'Travel Channel .',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Travel_Channel',
    logo: '/images/domains/bTLD/travelchannel.svg',
    promoImg: '/images/domains/bTLD/travelchannel.svg',
  },
  {
    name: '.travelers',
    entity: 'Travelers.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/The_Travelers_Companies',
    logo: '/images/domains/bTLD/travelers.svg',
    promoImg: '/images/domains/bTLD/travelers.svg',
  },
  {
    name: '.tui',
    entity: 'TUI.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/TUI_Group',
    logo: '/images/domains/bTLD/tui.svg',
    promoImg: '/images/domains/bTLD/tui.svg',
  },
  {
    name: '.tvs',
    entity: 'TVS.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/TVS_Group',
    logo: '/images/domains/bTLD/tvs.svg',
    promoImg: '/images/domains/bTLD/tvs.svg',
  },

]

export default data
