const data = [
  {
    name: '.macys',
    entity: `Macy's.`,
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Macy%27s,_Inc.',
    logo: '/images/domains/bTLD/macys.svg',
    promoImg: '/images/domains/bTLD/macys.svg',
  },
  {
    name: '.maif',
    entity: '.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Mutuelle Assurance Instituteur France (MAIF).`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/maif.svg',
    promoImg: '/images/domains/bTLD/maif.svg',
  },
  {
    name: '.man',
    entity: 'MAN.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/MAN_SE',
    logo: '/images/domains/bTLD/man.svg',
    promoImg: '/images/domains/bTLD/man.svg',
  },
  {
    name: '.mango',
    entity: 'Mango.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Mango_(retailer)',
    logo: '/images/domains/bTLD/mango.svg',
    promoImg: '/images/domains/bTLD/mango.svg',
  },
  {
    name: '.marriott',
    entity: 'Marriott.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Marriott_International',
    logo: '/images/domains/bTLD/marriott.svg',
    promoImg: '/images/domains/bTLD/marriott.svg',
  },
  {
    name: '.maserati',
    entity: 'Maserati.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Maserati',
    logo: '/images/domains/bTLD/maserati.svg',
    promoImg: '/images/domains/bTLD/maserati.svg',
  },
  {
    name: '.mattel',
    entity: 'Mattel.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Mattel',
    logo: '/images/domains/bTLD/mattel.svg',
    promoImg: '/images/domains/bTLD/mattel.svg',
  },
  {
    name: '.mckinsey',
    entity: 'McKinsey.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/McKinsey_%26_Company',
    logo: '/images/domains/bTLD/mckinsey.svg',
    promoImg: '/images/domains/bTLD/mckinsey.svg',
  },
  {
    name: '.metlife',
    entity: 'MetLife.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/MetLife',
    logo: '/images/domains/bTLD/metlife.svg',
    promoImg: '/images/domains/bTLD/metlife.svg',
  },
  {
    name: '.microsoft',
    entity: 'Microsoft.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Microsoft',
    logo: '/images/domains/bTLD/microsoft.svg',
    promoImg: '/images/domains/bTLD/microsoft.svg',
  },
  {
    name: '.mini',
    entity: 'Mini.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Mini_(marque)',
    logo: '/images/domains/bTLD/mini.svg',
    promoImg: '/images/domains/bTLD/mini.svg',
  },
  {
    name: '.mit',
    entity: 'MIT.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia:
      'https://en.wikipedia.org/wiki/Massachusetts_Institute_of_Technology',
    logo: '/images/domains/bTLD/mit.svg',
    promoImg: '/images/domains/bTLD/mit.svg',
  },
  {
    name: '.mitsubishi',
    entity: 'Mitsubishi.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Mitsubishi_Corporation',
    logo: '/images/domains/bTLD/mitsubishi.svg',
    promoImg: '/images/domains/bTLD/mitsubishi.svg',
  },
  {
    name: '.mlb',
    entity: 'MLB.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/MLB_Advanced_Media',
    logo: '/images/domains/bTLD/mlb.svg',
    promoImg: '/images/domains/bTLD/mlb.svg',
  },
  {
    name: '.mma',
    entity: 'MMA IARD.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/mma.svg',
    promoImg: '/images/domains/bTLD/mma.svg',
  },
  {
    name: '.monash',
    entity: 'Monash.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Monash_University',
    logo: '/images/domains/bTLD/monash.svg',
    promoImg: '/images/domains/bTLD/monash.svg',
  },
  {
    name: '.mormon',
    entity: 'Mormon.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Church_of_Jesus_Christ_of_Latter-day_Saints',
    logo: '/images/domains/bTLD/mormon.svg',
    promoImg: '/images/domains/bTLD/mormon.svg',
  },
  {
    name: '.moto',
    entity: 'Motorola.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Motorola',
    logo: '/images/domains/bTLD/moto.svg',
    promoImg: '/images/domains/bTLD/moto.svg',
  },
  {
    name: '.movistar',
    entity: 'Movistar.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Movistar',
    logo: '/images/domains/bTLD/movistar.svg',
    promoImg: '/images/domains/bTLD/movistar.svg',
  },
  {
    name: '.msd',
    entity: 'MSD.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`MSD Registry Holdings, Inc.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/msd.svg',
    promoImg: '/images/domains/bTLD/msd.svg',
  },
  {
    name: '.mtn',
    entity: 'MTN.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/MTN_Group',
    logo: '/images/domains/bTLD/mtn.svg',
    promoImg: '/images/domains/bTLD/mtn.svg',
  },
  {
    name: '.mtr',
    entity: 'MTR.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/MTR_Corporation',
    logo: '/images/domains/bTLD/mtr.svg',
    promoImg: '/images/domains/bTLD/mtr.svg',
  },
  {
    name: '.mutual',
    entity: 'Mutual.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Northwestern_Mutual',
    logo: '/images/domains/bTLD/mutual.svg',
    promoImg: '/images/domains/bTLD/mutual.svg',
  },
]

export default data
