const data = [
  {
    name: '.aaa',
    entity: 'AAA.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [
      `American Automobile Association (AAA – commonly pronounced as "Triple A" but also pronounced as individual letters) is a federation of motor clubs throughout North America. AAA is a privately held not-for-profit national member association and service organization with over 60 million members[1] in the United States and Canada.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/American_Automobile_Association',
    logo: '/images/domains/bTLD/aaa.svg',
    promoImg: '/images/domains/bTLD/aaa.svg',
  },
  {
    name: '.aarp',
    entity: 'AARP.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [
      `AARP, formerly the American Association of Retired Persons, is an interest group in the United States focusing on issues affecting those over the age of fifty.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/AARP',
    logo: '/images/domains/bTLD/aarp.svg',
    promoImg: '/images/domains/bTLD/aarp.svg',
  },
  {
    name: '.abarth',
    entity: 'Abarth.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [
      `Fiat Chrysler Automobiles (Abarth).`,
      `Fiat Chrysler Automobiles N.V. (FCA), now part of Stellantis, was an Italian-American multinational corporation primarily known as a manufacturer of automobiles, commercial vehicles, auto parts and production systems.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Fiat_Chrysler_Automobiles',
    logo: '/images/domains/bTLD/abarth.svg',
    promoImg: '/images/domains/bTLD/abarth.svg',
  },
  {
    name: '.abb',
    entity: 'ABB.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`ABB Ltd. is a Swedish–Swiss multinational corporation.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/ABB',
    logo: '/images/domains/bTLD/abb.svg',
    promoImg: '/images/domains/bTLD/abb.svg',
  },
  {
    name: '.abbott',
    entity: 'Abbott.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [
      `Abbott Laboratories is an American multinational medical devices and health care.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Abbott_Laboratories',
    logo: '/images/domains/bTLD/abbott.svg',
    promoImg: '/images/domains/bTLD/abbott.svg',
  },
  {
    name: '.abbvie',
    entity: 'AbbVie.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`AbbVie Inc. is an American pharmaceutical company.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/AbbVie',
    logo: '/images/domains/bTLD/abbvie.svg',
    promoImg: '/images/domains/bTLD/abbvie.svg',
  },
  {
    name: '.abc',
    entity: 'ABC.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [
      `The American Broadcasting Company (ABC) is an American commercial broadcast television and radio network that serves as the flagship property of the Disney Entertainment division of the Walt Disney Company.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/American_Broadcasting_Company',
    logo: '/images/domains/bTLD/abc.svg',
    promoImg: '/images/domains/bTLD/abc.svg',
  },
  {
    name: '.accenture',
    entity: 'Accenture.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [
      `Accenture plc is a global multinational professional services company.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Accenture',
    logo: '/images/domains/bTLD/accenture.svg',
    promoImg: '/images/domains/bTLD/accenture.svg',
  },
  {
    name: '.aco',
    entity: 'ACO.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`ACO Severin Ahlmann GmbH & Co. KG.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/aco.svg',
    promoImg: '/images/domains/bTLD/aco.svg',
  },
  {
    name: '.aeg',
    entity: 'AEG.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Aktiebolaget Electrolux.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Electrolux',
    logo: '/images/domains/bTLD/aeg.svg',
    promoImg: '/images/domains/bTLD/aeg.svg',
  },
  {
    name: '.aetna',
    entity: 'Aetna Inc.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [
      `Aetna Inc. is an American managed health care company that sells traditional and consumer directed health care insurance and related services, such as medical, pharmaceutical, dental, behavioral health, long-term care, and disability plans, primarily through employer-paid (fully or partly) insurance and benefit programs, and through Medicare.`,
    ],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Aetna',
    logo: '/images/domains/bTLD/aetna.svg',
    promoImg: '/images/domains/bTLD/aetna.svg',
  },
  {
    name: '.afl',
    entity: 'AFL.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Australian_Football_League',
    logo: '/images/domains/bTLD/afl.svg',
    promoImg: '/images/domains/bTLD/afl.svg',
  },
  {
    name: '.agakhan',
    entity: 'Aga Khan.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Aga Khan Foundation.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Aga_Khan_Foundation',
    logo: '/images/domains/bTLD/agakhan.svg',
    promoImg: '/images/domains/bTLD/agakhan.svg',
  },
  {
    name: '.aig',
    entity: 'AIG.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`American International Group, Inc. (AIG)`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/American_International_Group',
    logo: '/images/domains/bTLD/aig.svg',
    promoImg: '/images/domains/bTLD/aig.svg',
  },
  {
    name: '.aigo',
    entity: 'Aigo.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Aigo',
    logo: '/images/domains/bTLD/aigo.svg',
    promoImg: '/images/domains/bTLD/aigo.svg',
  },
  {
    name: '.airbus',
    entity: 'Airbus.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Airbus.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Airbus',
    logo: '/images/domains/bTLD/airbus.svg',
    promoImg: '/images/domains/bTLD/airbus.svg',
  },
  {
    name: '.airtel',
    entity: 'Airtel.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Bharti Airtel.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bharti_Airtel',
    logo: '/images/domains/bTLD/airtel.svg',
    promoImg: '/images/domains/bTLD/airtel.svg',
  },
  {
    name: '.akdn',
    entity: 'Aga Khan.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Aga Khan Foundation.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Aga_Khan_Foundation',
    logo: '/images/domains/bTLD/akdn.svg',
    promoImg: '/images/domains/bTLD/akdn.svg',
  },
  {
    name: '.alfaromeo',
    entity: 'Alfa Romeo.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Alfa Romeo.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Alfa_Romeo',
    logo: '/images/domains/bTLD/alfaromeo.svg',
    promoImg: '/images/domains/bTLD/alfaromeo.svg',
  },
  {
    name: '.alibaba',
    entity: 'Alibaba.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Alibaba Group.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Alibaba_Group',
    logo: '/images/domains/bTLD/alibaba.svg',
    promoImg: '/images/domains/bTLD/alibaba.svg',
  },
  {
    name: '.alipay',
    entity: 'Alibaba.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Alibaba Group.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Alibaba_Group',
    logo: '/images/domains/bTLD/alipay.svg',
    promoImg: '/images/domains/bTLD/alipay.svg',
  },
  {
    name: '.allfinanz',
    entity: 'Allfinanz.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Allfinanz Deutsche Vermögensberatung Aktiengesellschaft.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/allfinanz.svg',
    promoImg: '/images/domains/bTLD/allfinanz.svg',
  },
  {
    name: '.allstate',
    entity: 'Allstate.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Allstate',
    logo: '/images/domains/bTLD/allstate.svg',
    promoImg: '/images/domains/bTLD/allstate.svg',
  },
  {
    name: '.ally',
    entity: 'Ally.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Ally Financial.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Ally_Financial',
    logo: '/images/domains/bTLD/ally.svg',
    promoImg: '/images/domains/bTLD/ally.svg',
  },
  {
    name: '.alstom',
    entity: 'Alstom.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Alstom',
    logo: '/images/domains/bTLD/alstom.svg',
    promoImg: '/images/domains/bTLD/alstom.svg',
  },
  {
    name: '.amazon',
    entity: 'Amazon.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/.amazon',
    logo: '/images/domains/bTLD/amazon.svg',
    promoImg: '/images/domains/bTLD/amazon.svg',
  },
  {
    name: '.americanexpress',
    entity: 'American Express.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/American_Express',
    logo: '/images/domains/bTLD/americanexpress.svg',
    promoImg: '/images/domains/bTLD/americanexpress.svg',
  },
  {
    name: '.amex',
    entity: 'American Express.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/American_Express',
    logo: '/images/domains/bTLD/amex.svg',
    promoImg: '/images/domains/bTLD/amex.svg',
  },
  {
    name: '.amica',
    entity: 'Amica.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Amica_Mutual_Insurance',
    logo: '/images/domains/bTLD/amica.svg',
    promoImg: '/images/domains/bTLD/amica.svg',
  },
  {
    name: '.android',
    entity: 'Android.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Android_(operating_system)',
    logo: '/images/domains/bTLD/android.svg',
    promoImg: '/images/domains/bTLD/android.svg',
  },
  {
    name: '.anz',
    entity: 'ANZ bank.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/ANZ_(bank)',
    logo: '/images/domains/bTLD/anz.svg',
    promoImg: '/images/domains/bTLD/anz.svg',
  },
  {
    name: '.aol',
    entity: 'AOL.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/AOL',
    logo: '/images/domains/bTLD/aol.svg',
    promoImg: '/images/domains/bTLD/aol.svg',
  },
  {
    name: '.apple',
    entity: 'Apple Inc.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Apple_Inc.',
    logo: '/images/domains/bTLD/apple.svg',
    promoImg: '/images/domains/bTLD/apple.svg',
  },
  {
    name: '.aquarelle',
    entity: 'Aquarelle.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Aquarelle.com_Group',
    logo: '/images/domains/bTLD/aquarelle.svg',
    promoImg: '/images/domains/bTLD/aquarelle.svg',
  },
  {
    name: '.aramco',
    entity: 'Saudi Aramco.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Saudi_Aramco',
    logo: '/images/domains/bTLD/aramco.svg',
    promoImg: '/images/domains/bTLD/aramco.svg',
  },
  {
    name: '.audi',
    entity: 'Audi AG.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Audi',
    logo: '/images/domains/bTLD/audi.svg',
    promoImg: '/images/domains/bTLD/audi.svg',
  },
  {
    name: '.auspost',
    entity: 'Australia Post.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Australia_Post',
    logo: '/images/domains/bTLD/auspost.svg',
    promoImg: '/images/domains/bTLD/auspost.svg',
  },
  {
    name: '.aws',
    entity: 'AWS.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Amazon Web Services.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Amazon_Web_Services',
    logo: '/images/domains/bTLD/aws.svg',
    promoImg: '/images/domains/bTLD/aws.svg',
  },
  {
    name: '.axa',
    entity: 'Axa.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Axa',
    logo: '/images/domains/bTLD/axa.svg',
    promoImg: '/images/domains/bTLD/axa.svg',
  },
  {
    name: '.azure',
    entity: 'Azure.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Microsoft',
    logo: '/images/domains/bTLD/azure.svg',
    promoImg: '/images/domains/bTLD/azure.svg',
  },

]

export default data
