const data = [
  {
    name: '.fage',
    entity: 'Fage.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Fage',
    logo: '/images/domains/bTLD/fage.svg',
    promoImg: '/images/domains/bTLD/fage.svg',
  },
  {
    name: '.fairwinds',
    entity: 'FairWinds.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/fairwinds.svg',
    promoImg: '/images/domains/bTLD/fairwinds.svg',
  },
  {
    name: '.farmers',
    entity: 'Farmers.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Farmers_Insurance_Group',
    logo: '/images/domains/bTLD/farmers.svg',
    promoImg: '/images/domains/bTLD/farmers.svg',
  },
  {
    name: '.fedex',
    entity: 'FedEx.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/FedEx',
    logo: '/images/domains/bTLD/fedex.svg',
    promoImg: '/images/domains/bTLD/fedex.svg',
  },
  {
    name: '.ferrari',
    entity: 'Ferrari.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Ferrari',
    logo: '/images/domains/bTLD/ferrari.svg',
    promoImg: '/images/domains/bTLD/ferrari.svg',
  },
  {
    name: '.ferrero',
    entity: 'Ferrero.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Ferrero_SpA',
    logo: '/images/domains/bTLD/ferrero.svg',
    promoImg: '/images/domains/bTLD/ferrero.svg',
  },
  {
    name: '.fiat',
    entity: 'Fiat.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Fiat_Chrysler_Automobiles',
    logo: '/images/domains/bTLD/fiat.svg',
    promoImg: '/images/domains/bTLD/fiat.svg',
  },
  {
    name: '.fidelity',
    entity: 'Fidelity.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Fidelity_Investments',
    logo: '/images/domains/bTLD/fidelity.svg',
    promoImg: '/images/domains/bTLD/fidelity.svg',
  },
  {
    name: '.firestone',
    entity: 'Firestone.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Bridgestone',
    logo: '/images/domains/bTLD/firestone.svg',
    promoImg: '/images/domains/bTLD/firestone.svg',
  },
  {
    name: '.firmdale',
    entity: 'Firmdale.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Firmdale Holdings.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/firmdale.svg',
    promoImg: '/images/domains/bTLD/firmdale.svg',
  },
  {
    name: '.flickr',
    entity: 'Flickr.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Flickr',
    logo: '/images/domains/bTLD/flickr.svg',
    promoImg: '/images/domains/bTLD/flickr.svg',
  },
  {
    name: '.flir',
    entity: 'FLIR.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Teledyne_FLIR',
    logo: '/images/domains/bTLD/flir.svg',
    promoImg: '/images/domains/bTLD/flir.svg',
  },
  {
    name: '.flsmidth',
    entity: 'FLSmidth.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/FLSmidth',
    logo: '/images/domains/bTLD/flsmidth.svg',
    promoImg: '/images/domains/bTLD/flsmidth.svg',
  },
  {
    name: '.ford',
    entity: 'Ford.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Ford_Motor_Company',
    logo: '/images/domains/bTLD/ford.svg',
    promoImg: '/images/domains/bTLD/ford.svg',
  },
  {
    name: '.fox',
    entity: 'Fox.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Fox_Broadcasting_Company',
    logo: '/images/domains/bTLD/fox.svg',
    promoImg: '/images/domains/bTLD/fox.svg',
  },
  {
    name: '.fresenius',
    entity: 'Fresenius.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Fresenius Immobilien-Verwaltungs-GmbH.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/fresenius.svg',
    promoImg: '/images/domains/bTLD/fresenius.svg',
  },
  {
    name: '.forex',
    entity: 'Forex.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: 'Dotforex Registry Ltd',
      link: '',
    },
    notes: [`Dotforex Registry Ltd`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/forex.svg',
    promoImg: '/images/domains/bTLD/forex.svg',
  },
  {
    name: '.frogans',
    entity: 'OP3FT.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Solely for use by the Frogans technology.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/frogans.svg',
    promoImg: '/images/domains/bTLD/frogans.svg',
  },
  {
    name: '.frontier',
    entity: 'Frontier.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Frontier_Communications',
    logo: '/images/domains/bTLD/frontier.svg',
    promoImg: '/images/domains/bTLD/frontier.svg',
  },
  {
    name: '.fujitsu',
    entity: 'Fujitsu.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Fujitsu',
    logo: '/images/domains/bTLD/fujitsu.svg',
    promoImg: '/images/domains/bTLD/fujitsu.svg',
  },
  {
    name: '.fujixerox',
    entity: 'Fujifilm.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Fujifilm_Business_Innovation',
    logo: '/images/domains/bTLD/fujixerox.svg',
    promoImg: '/images/domains/bTLD/fujixerox.svg',
  },

]

export default data
