const data = [
  {
    name: '.verisign',
    entity: 'Verisign.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Verisign',
    logo: '/images/domains/bTLD/verisign.svg',
    promoImg: '/images/domains/bTLD/verisign.svg',
  },
  {
    name: '.vig',
    entity: 'VIG.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Vienna_Insurance_Group',
    logo: '/images/domains/bTLD/vig.svg',
    promoImg: '/images/domains/bTLD/vig.svg',
  },
  {
    name: '.viking',
    entity: 'Viking.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Viking_(cruise_line)',
    logo: '/images/domains/bTLD/viking.svg',
    promoImg: '/images/domains/bTLD/viking.svg',
  },
  {
    name: '.virgin',
    entity: 'Virgin.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Virgin_Group',
    logo: '/images/domains/bTLD/virgin.svg',
    promoImg: '/images/domains/bTLD/virgin.svg',
  },
  {
    name: '.visa',
    entity: 'Visa.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Visa_Inc.',
    logo: '/images/domains/bTLD/visa.svg',
    promoImg: '/images/domains/bTLD/visa.svg',
  },
  {
    name: '.vista',
    entity: 'Vistaprint.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Vistaprint',
    logo: '/images/domains/bTLD/vista.svg',
    promoImg: '/images/domains/bTLD/vista.svg',
  },
  {
    name: '.vistaprint',
    entity: 'Vistaprint.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Vistaprint',
    logo: '/images/domains/bTLD/vistaprint.svg',
    promoImg: '/images/domains/bTLD/vistaprint.svg',
  },
  {
    name: '.vivo',
    entity: 'Vivo.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Telef%C3%B4nica_Brasil',
    logo: '/images/domains/bTLD/vivo.svg',
    promoImg: '/images/domains/bTLD/vivo.svg',
  },
  {
    name: '.volkswagen',
    entity: 'Volkswagen.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Volkswagen_Group_of_America',
    logo: '/images/domains/bTLD/volkswagen.svg',
    promoImg: '/images/domains/bTLD/volkswagen.svg',
  },
  {
    name: '.volvo',
    entity: 'Volvo.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Volvo',
    logo: '/images/domains/bTLD/volvo.svg',
    promoImg: '/images/domains/bTLD/volvo.svg',
  },
]

export default data
