const data = [
  {
    name: '.walmart',
    entity: 'Walmart.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Walmart',
    logo: '/images/domains/bTLD/walmart.svg',
    promoImg: '/images/domains/bTLD/walmart.svg',
  },

  {
    name: '.weatherchannel',
    entity: 'Weather Company.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/The_Weather_Company',
    logo: '/images/domains/bTLD/weatherchannel.svg',
    promoImg: '/images/domains/bTLD/weatherchannel.svg',
  },
  {
    name: '.weber',
    entity: 'Weber.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Saint-Gobain',
    logo: '/images/domains/bTLD/weber.svg',
    promoImg: '/images/domains/bTLD/weber.svg',
  },
  {
    name: '.weir',
    entity: 'Weir.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Weir_Group',
    logo: '/images/domains/bTLD/weir.svg',
    promoImg: '/images/domains/bTLD/weir.svg',
  },
  {
    name: '.williamhill',
    entity: 'William Hill.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/William_Hill_(bookmaker)',
    logo: '/images/domains/bTLD/williamhill.svg',
    promoImg: '/images/domains/bTLD/williamhill.svg',
  },
  {
    name: '.windows',
    entity: 'Windows.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Microsoft_Windows',
    logo: '/images/domains/bTLD/windows.svg',
    promoImg: '/images/domains/bTLD/windows.svg',
  },
  {
    name: '.wme',
    entity: 'WME.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Endeavor_(company)',
    logo: '/images/domains/bTLD/wme.svg',
    promoImg: '/images/domains/bTLD/wme.svg',
  },
  {
    name: '.wolterskluwer',
    entity: 'Wolters Kluwer.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Wolters_Kluwer',
    logo: '/images/domains/bTLD/wolterskluwer.svg',
    promoImg: '/images/domains/bTLD/wolterskluwer.svg',
  },
  {
    name: '.woodside',
    entity: 'Woodside.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Woodside_Energy',
    logo: '/images/domains/bTLD/woodside.svg',
    promoImg: '/images/domains/bTLD/woodside.svg',
  },
  {
    name: '.wtc',
    entity: 'WTC.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/World_Trade_Centers_Association',
    logo: '/images/domains/bTLD/wtc.svg',
    promoImg: '/images/domains/bTLD/wtc.svg',
  },
 
]

export default data
