const data = [
  {
    name: '.xbox',
    entity: 'Xbox.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Xbox',
    logo: '/images/domains/bTLD/xbox.svg',
    promoImg: '/images/domains/bTLD/xbox.svg',
  },
  {
    name: '.xerox',
    entity: 'Xerox.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Fujifilm_Business_Innovation',
    logo: '/images/domains/bTLD/xerox.svg',
    promoImg: '/images/domains/bTLD/xerox.svg',
  },
  {
    name: '.xfinity',
    entity: 'Xfinity.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Comcast',
    logo: '/images/domains/bTLD/xfinity.svg',
    promoImg: '/images/domains/bTLD/xfinity.svg',
  },

]

export default data
