const data = [
  {
    name: '.safety',
    entity: 'Safety.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'Safety Registry Services, LLC.',
    logo: '/images/domains/bTLD/safety.svg',
    promoImg: '/images/domains/bTLD/safety.svg',
  },
  {
    name: '.sakura',
    entity: 'Sakura.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sakura_Internet',
    logo: '/images/domains/bTLD/sakura.svg',
    promoImg: '/images/domains/bTLD/sakura.svg',
  },
  {
    name: '.samsung',
    entity: 'Samsung.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Samsung_SDS',
    logo: '/images/domains/bTLD/samsung.svg',
    promoImg: '/images/domains/bTLD/samsung.svg',
  },
  {
    name: '.sandvik',
    entity: 'Sandvik.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sandvik',
    logo: '/images/domains/bTLD/sandvik.svg',
    promoImg: '/images/domains/bTLD/sandvik.svg',
  },
  {
    name: '.sandvikcoromant',
    entity: 'Sandvik.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sandvik_Coromant',
    logo: '/images/domains/bTLD/sandvikcoromant.svg',
    promoImg: '/images/domains/bTLD/sandvikcoromant.svg',
  },
  {
    name: '.sanofi',
    entity: 'Sanofi.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sanofi',
    logo: '/images/domains/bTLD/sanofi.svg',
    promoImg: '/images/domains/bTLD/sanofi.svg',
  },
  {
    name: '.sap',
    entity: 'SAP.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SAP',
    logo: '/images/domains/bTLD/sap.svg',
    promoImg: '/images/domains/bTLD/sap.svg',
  },
  {
    name: '.saxo',
    entity: 'Saxo Bank.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Saxo_Bank',
    logo: '/images/domains/bTLD/saxo.svg',
    promoImg: '/images/domains/bTLD/saxo.svg',
  },
  {
    name: '.sbi',
    entity: 'SBI.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/State_Bank_of_India',
    logo: '/images/domains/bTLD/sbi.svg',
    promoImg: '/images/domains/bTLD/sbi.svg',
  },
  {
    name: '.sbs',
    entity: 'SBS.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Special_Broadcasting_Service',
    logo: '/images/domains/bTLD/sbs.svg',
    promoImg: '/images/domains/bTLD/sbs.svg',
  },
  {
    name: '.sca',
    entity: 'SCA.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SCA_(company)',
    logo: '/images/domains/bTLD/sca.svg',
    promoImg: '/images/domains/bTLD/sca.svg',
  },
  {
    name: '.scb',
    entity: 'SCB.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Siam_Commercial_Bank',
    logo: '/images/domains/bTLD/scb.svg',
    promoImg: '/images/domains/bTLD/scb.svg',
  },
  {
    name: '.schaeffler',
    entity: 'Schaeffler.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Schaeffler_Group',
    logo: '/images/domains/bTLD/schaeffler.svg',
    promoImg: '/images/domains/bTLD/schaeffler.svg',
  },
  {
    name: '.schmidt',
    entity: 'Schmidt.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Société Alsacienne de Meubles (Cuisines Schmidt).`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/schmidt.svg',
    promoImg: '/images/domains/bTLD/schmidt.svg',
  },
  {
    name: '.schwarz',
    entity: 'Schwarz.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Schwarz_Gruppe',
    logo: '/images/domains/bTLD/schwarz.svg',
    promoImg: '/images/domains/bTLD/schwarz.svg',
  },
  {
    name: '.scjohnson',
    entity: 'S.C.Johnson.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/S._C._Johnson_%26_Son',
    logo: '/images/domains/bTLD/scjohnson.svg',
    promoImg: '/images/domains/bTLD/scjohnson.svg',
  },
  {
    name: '.scor',
    entity: 'SCOR.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SCOR_SE',
    logo: '/images/domains/bTLD/scor.svg',
    promoImg: '/images/domains/bTLD/scor.svg',
  },
  {
    name: '.seat',
    entity: 'SEAT.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SEAT',
    logo: '/images/domains/bTLD/seat.svg',
    promoImg: '/images/domains/bTLD/seat.svg',
  },
  {
    name: '.sener',
    entity: 'SENER.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SENER',
    logo: '/images/domains/bTLD/sener.svg',
    promoImg: '/images/domains/bTLD/sener.svg',
  },
  {
    name: '.ses',
    entity: 'SES.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SES_(company)',
    logo: '/images/domains/bTLD/ses.svg',
    promoImg: '/images/domains/bTLD/ses.svg',
  },
  {
    name: '.sew',
    entity: 'Eurodrive.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SEW_Eurodrive',
    logo: '/images/domains/bTLD/sew.svg',
    promoImg: '/images/domains/bTLD/sew.svg',
  },
  {
    name: '.seven',
    entity: 'Seven.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Seven_West_Media',
    logo: '/images/domains/bTLD/seven.svg',
    promoImg: '/images/domains/bTLD/seven.svg',
  },
  {
    name: '.sfr',
    entity: 'SFR.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SFR',
    logo: '/images/domains/bTLD/sfr.svg',
    promoImg: '/images/domains/bTLD/sfr.svg',
  },
  {
    name: '.seek',
    entity: 'SEEK.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SEEK',
    logo: '/images/domains/bTLD/seek.svg',
    promoImg: '/images/domains/bTLD/seek.svg',
  },
  {
    name: '.shangrila',
    entity: 'Shangri-La.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Shangri-La_Hotels_and_Resorts',
    logo: '/images/domains/bTLD/shangrila.svg',
    promoImg: '/images/domains/bTLD/shangrila.svg',
  },
  {
    name: '.sharp',
    entity: 'Sharp.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sharp_Corporation',
    logo: '/images/domains/bTLD/sharp.svg',
    promoImg: '/images/domains/bTLD/sharp.svg',
  },
  {
    name: '.shaw',
    entity: 'Shaw.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Shaw_Communications',
    logo: '/images/domains/bTLD/shaw.svg',
    promoImg: '/images/domains/bTLD/shaw.svg',
  },
  {
    name: '.shell',
    entity: 'Shell.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Shell_plc',
    logo: '/images/domains/bTLD/shell.svg',
    promoImg: '/images/domains/bTLD/shell.svg',
  },
  {
    name: '.shriram',
    entity: 'Shriram.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Shriram_Group',
    logo: '/images/domains/bTLD/shriram.svg',
    promoImg: '/images/domains/bTLD/shriram.svg',
  },
  {
    name: '.sina',
    entity: 'Sina.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sina_Corporation',
    logo: '/images/domains/bTLD/sina.svg',
    promoImg: '/images/domains/bTLD/sina.svg',
  },
  {
    name: '.sky',
    entity: 'Sky.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sky_Group',
    logo: '/images/domains/bTLD/sky.svg',
    promoImg: '/images/domains/bTLD/sky.svg',
  },
  {
    name: '.skype',
    entity: 'Skype.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Skype',
    logo: '/images/domains/bTLD/skype.svg',
    promoImg: '/images/domains/bTLD/skype.svg',
  },
  {
    name: '.smart',
    entity: 'Smart.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Smart_Communications',
    logo: '/images/domains/bTLD/smart.svg',
    promoImg: '/images/domains/bTLD/smart.svg',
  },
  {
    name: '.sncf',
    entity: 'SNCF.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SNCF',
    logo: '/images/domains/bTLD/sncf.svg',
    promoImg: '/images/domains/bTLD/sncf.svg',
  },
  {
    name: '.softbank',
    entity: 'SoftBank.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/SoftBank_Group',
    logo: '/images/domains/bTLD/softbank.svg',
    promoImg: '/images/domains/bTLD/softbank.svg',
  },
  {
    name: '.sohu',
    entity: 'Sohu.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sohu',
    logo: '/images/domains/bTLD/sohu.svg',
    promoImg: '/images/domains/bTLD/sohu.svg',
  },
  {
    name: '.sony',
    entity: 'Sony.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Sony',
    logo: '/images/domains/bTLD/sony.svg',
    promoImg: '/images/domains/bTLD/sony.svg',
  },
  {
    name: '.spiegel',
    entity: 'Der Spiegel.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Der_Spiegel',
    logo: '/images/domains/bTLD/spiegel.svg',
    promoImg: '/images/domains/bTLD/spiegel.svg',
  },
  {
    name: '.stada',
    entity: 'Stada.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Stada_Arzneimittel',
    logo: '/images/domains/bTLD/stada.svg',
    promoImg: '/images/domains/bTLD/stada.svg',
  },
  {
    name: '.staples',
    entity: 'Staples.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Staples_Inc.',
    logo: '/images/domains/bTLD/staples.svg',
    promoImg: '/images/domains/bTLD/staples.svg',
  },
  {
    name: '.star',
    entity: 'Star.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Disney_Star',
    logo: '/images/domains/bTLD/star.svg',
    promoImg: '/images/domains/bTLD/star.svg',
  },
  {
    name: '.starhub',
    entity: 'StarHub.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/StarHub',
    logo: '/images/domains/bTLD/starhub.svg',
    promoImg: '/images/domains/bTLD/starhub.svg',
  },
  {
    name: '.statebank',
    entity: 'State Bank.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/State_Bank_of_India',
    logo: '/images/domains/bTLD/statebank.svg',
    promoImg: '/images/domains/bTLD/statebank.svg',
  },
  {
    name: '.statefarm',
    entity: 'State Farm.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/State_Farm',
    logo: '/images/domains/bTLD/statefarm.svg',
    promoImg: '/images/domains/bTLD/statefarm.svg',
  },
  {
    name: '.statoil',
    entity: 'Statoil.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Equinor',
    logo: '/images/domains/bTLD/statoil.svg',
    promoImg: '/images/domains/bTLD/statoil.svg',
  },
  {
    name: '.stc',
    entity: 'STC.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Saudi_Telecom_Company',
    logo: '/images/domains/bTLD/stc.svg',
    promoImg: '/images/domains/bTLD/stc.svg',
  },
  {
    name: '.stcgroup',
    entity: 'STC group.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Stc_Group',
    logo: '/images/domains/bTLD/stcgroup.svg',
    promoImg: '/images/domains/bTLD/stcgroup.svg',
  },
  {
    name: '.suzuki',
    entity: 'Suzuki.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Suzuki',
    logo: '/images/domains/bTLD/suzuki.svg',
    promoImg: '/images/domains/bTLD/suzuki.svg',
  },
  {
    name: '.swatch',
    entity: 'Swatch.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/The_Swatch_Group',
    logo: '/images/domains/bTLD/swatch.svg',
    promoImg: '/images/domains/bTLD/swatch.svg',
  },
  {
    name: '.swiftcover',
    entity: 'Swiftcover.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Axa#Swiftcover',
    logo: '/images/domains/bTLD/swiftcover.svg',
    promoImg: '/images/domains/bTLD/swiftcover.svg',
  },
  {
    name: '.symantec',
    entity: 'Symantec.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Gen_Digital',
    logo: '/images/domains/bTLD/symantec.svg',
    promoImg: '/images/domains/bTLD/symantec.svg',
  },

]

export default data
