const data = [
  {
    name: '.yahoo',
    entity: 'Yahoo.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Yahoo',
    logo: '/images/domains/bTLD/yahoo.svg',
    promoImg: '/images/domains/bTLD/yahoo.svg',
  },
  {
    name: '.yamaxun',
    entity: 'Yamaxun.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Amazon_China',
    logo: '/images/domains/bTLD/yamaxun.svg',
    promoImg: '/images/domains/bTLD/yamaxun.svg',
  },
  {
    name: '.yandex',
    entity: 'Yandex.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Yandex',
    logo: '/images/domains/bTLD/yandex.svg',
    promoImg: '/images/domains/bTLD/yandex.svg',
  },
  {
    name: '.yodobashi',
    entity: 'Yodobashi.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Yodobashi_Camera',
    logo: '/images/domains/bTLD/yodobashi.svg',
    promoImg: '/images/domains/bTLD/yodobashi.svg',
  },
  {
    name: '.youtube',
    entity: 'YouTube.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/YouTube',
    logo: '/images/domains/bTLD/youtube.svg',
    promoImg: '/images/domains/bTLD/youtube.svg',
  },
  
]

export default data
