const data = [
  {
    name: '.dabur',
    entity: 'Dabur.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Dabur',
    logo: '/images/domains/bTLD/dabur.svg',
    promoImg: '/images/domains/bTLD/dabur.svg',
  },
  {
    name: '.datsun',
    entity: 'Datsun.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Datsun',
    logo: '/images/domains/bTLD/datsun.svg',
    promoImg: '/images/domains/bTLD/datsun.svg',
  },
  {
    name: '.dealer',
    entity: 'Dealer Dot Com.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/dealer.svg',
    promoImg: '/images/domains/bTLD/dealer.svg',
  },
  {
    name: '.dell',
    entity: 'Dell.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Dell',
    logo: '/images/domains/bTLD/dell.svg',
    promoImg: '/images/domains/bTLD/dell.svg',
  },
  {
    name: '.deloitte',
    entity: 'Deloitte.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Deloitte',
    logo: '/images/domains/bTLD/deloitte.svg',
    promoImg: '/images/domains/bTLD/deloitte.svg',
  },
  {
    name: '.delta',
    entity: 'Delta.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Delta_Air_Lines',
    logo: '/images/domains/bTLD/delta.svg',
    promoImg: '/images/domains/bTLD/delta.svg',
  },
  {
    name: '.dhl',
    entity: 'Deutsche Post.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Deutsche_Post',
    logo: '/images/domains/bTLD/dhl.svg',
    promoImg: '/images/domains/bTLD/dhl.svg',
  },
  {
    name: '.discover',
    entity: 'Discover.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Discover Financial Services.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/discover.svg',
    promoImg: '/images/domains/bTLD/discover.svg',
  },
  {
    name: '.dish',
    entity: 'Dish.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Dish_Network',
    logo: '/images/domains/bTLD/dish.svg',
    promoImg: '/images/domains/bTLD/dish.svg',
  },
  {
    name: '.dnp',
    entity: 'Dai Nippon.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Dai_Nippon_Printing',
    logo: '/images/domains/bTLD/dnp.svg',
    promoImg: '/images/domains/bTLD/dnp.svg',
  },
  {
    name: '.dodge',
    entity: 'Dodge.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Dodge',
    logo: '/images/domains/bTLD/dodge.svg',
    promoImg: '/images/domains/bTLD/dodge.svg',
  },
  {
    name: '.dunlop',
    entity: 'Dunlop.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Dunlop Tyres.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Dunlop_Tyres',
    logo: '/images/domains/bTLD/dunlop.svg',
    promoImg: '/images/domains/bTLD/dunlop.svg',
  },
  {
    name: '.dupont',
    entity: 'DuPont.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/DuPont',
    logo: '/images/domains/bTLD/dupont.svg',
    promoImg: '/images/domains/bTLD/dupont.svg',
  },
  {
    name: '.dvag',
    entity: 'Deutsche Vag.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Deutsche_Verm%C3%B6gensberatung',
    logo: '/images/domains/bTLD/dvag.svg',
    promoImg: '/images/domains/bTLD/dvag.svg',
  },

]

export default data
