const data = [
  {
    name: '.jaguar',
    entity: 'Jaguar.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Jaguar_Land_Rover',
    logo: '/images/domains/bTLD/jaguar.svg',
    promoImg: '/images/domains/bTLD/jaguar.svg',
  },
  {
    name: '.java',
    entity: 'Java.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Java_(programming_language)',
    logo: '/images/domains/bTLD/java.svg',
    promoImg: '/images/domains/bTLD/java.svg',
  },
  {
    name: '.jcb',
    entity: 'JCB.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/JCB_(credit_card_company)',
    logo: '/images/domains/bTLD/jcb.svg',
    promoImg: '/images/domains/bTLD/jcb.svg',
  },
  {
    name: '.jcp',
    entity: '.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/jcp.svg',
    promoImg: '/images/domains/bTLD/.svg',
  },
  {
    name: '.jeep',
    entity: 'Jeep.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Jeep',
    logo: '/images/domains/bTLD/jeep.svg',
    promoImg: '/images/domains/bTLD/jeep.svg',
  },
  {
    name: '.jio',
    entity: 'Jio.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Jio',
    logo: '/images/domains/bTLD/jio.svg',
    promoImg: '/images/domains/bTLD/jio.svg',
  },
  {
    name: '.jpmorgan',
    entity: 'JPMorgan.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/JPMorgan_Chase',
    logo: '/images/domains/bTLD/jpmorgan.svg',
    promoImg: '/images/domains/bTLD/jpmorgan.svg',
  },
  {
    name: '.juniper',
    entity: 'Juniper.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Juniper_Networks',
    logo: '/images/domains/bTLD/juniper.svg',
    promoImg: '/images/domains/bTLD/juniper.svg',
  },

]

export default data
