const data = [
  {
    name: '.lacaixa',
    entity: 'La Caixa.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/La_Caixa',
    logo: '/images/domains/bTLD/lacaixa.svg',
    promoImg: '/images/domains/bTLD/lacaixa.svg',
  },
  {
    name: '.ladbrokes',
    entity: 'Ladbrokes.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Ladbrokes_Coral',
    logo: '/images/domains/bTLD/ladbrokes.svg',
    promoImg: '/images/domains/bTLD/ladbrokes.svg',
  },
  {
    name: '.lamborghini',
    entity: 'Lamborghini.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lamborghini',
    logo: '/images/domains/bTLD/lamborghini.svg',
    promoImg: '/images/domains/bTLD/lamborghini.svg',
  },
  {
    name: '.lancaster',
    entity: 'Lancaster.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Coty',
    logo: '/images/domains/bTLD/lancaster.svg',
    promoImg: '/images/domains/bTLD/lancaster.svg',
  },
  {
    name: '.lancia',
    entity: 'Lancia.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lancia',
    logo: '/images/domains/bTLD/lancia.svg',
    promoImg: '/images/domains/bTLD/lancia.svg',
  },
  {
    name: '.lancome',
    entity: 'Lancome.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/L%27Or%C3%A9al',
    logo: '/images/domains/bTLD/lancome.svg',
    promoImg: '/images/domains/bTLD/lancome.svg',
  },
  {
    name: '.landrover',
    entity: 'Land Rover.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Jaguar_Land_Rover',
    logo: '/images/domains/bTLD/landrover.svg',
    promoImg: '/images/domains/bTLD/landrover.svg',
  },
  {
    name: '.lanxess',
    entity: 'Lanxess.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lanxess',
    logo: '/images/domains/bTLD/lanxess.svg',
    promoImg: '/images/domains/bTLD/lanxess.svg',
  },
  {
    name: '.lasalle',
    entity: '.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/JLL_(company)',
    logo: '/images/domains/bTLD/lasalle.svg',
    promoImg: '/images/domains/bTLD/lasalle.svg',
  },
  {
    name: '.latrobe',
    entity: 'La Trobe.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/La_Trobe_University',
    logo: '/images/domains/bTLD/latrobe.svg',
    promoImg: '/images/domains/bTLD/latrobe.svg',
  },
  {
    name: '.lds',
    entity: 'LDS.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia:
      'https://en.wikipedia.org/wiki/The_Church_of_Jesus_Christ_of_Latter-day_Saints',
    logo: '/images/domains/bTLD/lds.svg',
    promoImg: '/images/domains/bTLD/lds.svg',
  },
  {
    name: '.leclerc',
    entity: 'E.Leclerc.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/E.Leclerc',
    logo: '/images/domains/bTLD/leclerc.svg',
    promoImg: '/images/domains/bTLD/leclerc.svg',
  },
  {
    name: '.lego',
    entity: 'Lego.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/The_Lego_Group',
    logo: '/images/domains/bTLD/lego.svg',
    promoImg: '/images/domains/bTLD/lego.svg',
  },
  {
    name: '.liaison',
    entity: 'Liaison Technologies.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/liaison.svg',
    promoImg: '/images/domains/bTLD/liaison.svg',
  },
  {
    name: '.lexus',
    entity: 'Lexus.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lexus',
    logo: '/images/domains/bTLD/lexus.svg',
    promoImg: '/images/domains/bTLD/lexus.svg',
  },
  {
    name: '.lidl',
    entity: 'Lidl.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lidl',
    logo: '/images/domains/bTLD/lidl.svg',
    promoImg: '/images/domains/bTLD/lidl.svg',
  },
  {
    name: '.lifestyle',
    entity: 'Lifestyle.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Lifestyle Domain Holdings, Inc`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/lifestyle.svg',
    promoImg: '/images/domains/bTLD/lifestyle.svg',
  },
  {
    name: '.lilly',
    entity: 'Eli Lilly.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Eli Lilly and Company`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Eli_Lilly_and_Company',
    logo: '/images/domains/bTLD/lilly.svg',
    promoImg: '/images/domains/bTLD/lilly.svg',
  },
  {
    name: '.lincoln',
    entity: 'Lincoln.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lincoln_Motor_Company',
    logo: '/images/domains/bTLD/lincoln.svg',
    promoImg: '/images/domains/bTLD/lincoln.svg',
  },
  {
    name: '.linde',
    entity: 'Linde.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Linde_plc',
    logo: '/images/domains/bTLD/linde.svg',
    promoImg: '/images/domains/bTLD/linde.svg',
  },
  {
    name: '.lipsy',
    entity: 'Lipsy Ltd.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/lipsy.svg',
    promoImg: '/images/domains/bTLD/lipsy.svg',
  },
  {
    name: '.lixil',
    entity: 'Lixil.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lixil_Group',
    logo: '/images/domains/bTLD/lixil.svg',
    promoImg: '/images/domains/bTLD/lixil.svg',
  },
  {
    name: '.locus',
    entity: 'Locus.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Locus Analytics.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/locus.svg',
    promoImg: '/images/domains/bTLD/locus.svg',
  },
  {
    name: '.lotte',
    entity: 'Lotte.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lotte_Holdings',
    logo: '/images/domains/bTLD/lotte.svg',
    promoImg: '/images/domains/bTLD/lotte.svg',
  },
  {
    name: '.lpl',
    entity: 'LPL.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/LPL_Financial',
    logo: '/images/domains/bTLD/lpl.svg',
    promoImg: '/images/domains/bTLD/lpl.svg',
  },
  {
    name: '.lplfinancial',
    entity: 'LPL.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/LPL_Financial',
    logo: '/images/domains/bTLD/lplfinancial.svg',
    promoImg: '/images/domains/bTLD/lplfinancial.svg',
  },
  {
    name: '.lundbeck',
    entity: 'Lundbeck.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [``],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: 'https://en.wikipedia.org/wiki/Lundbeck',
    logo: '/images/domains/bTLD/lundbeck.svg',
    promoImg: '/images/domains/bTLD/lundbeck.svg',
  },
  {
    name: '.lupin',
    entity: '.',
    sponsor: {
      title: '',
      link: '',
    },
    administrator: {
      title: '',
      link: '',
    },
    notes: [`Lupin Limited.`],
    defaultPrice: 0,
    introduced: '',
    stats: '',
    multiplier: 1,
    idn: 0,
    dnssec: 0,
    sld: 0,
    ipv6: 0,
    id: 0,
    wikipedia: '',
    logo: '/images/domains/bTLD/lupin.svg',
    promoImg: '/images/domains/bTLD/lupin.svg',
  },

]

export default data
